<a href="https://colab.research.google.com/github/brpetros/prompts_and_evalution_notebooks/blob/main/1_skillab_data_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Log in and functions definition

In [ ]:
import requests
from pprint import pprint
from google.colab import userdata
import os

BASE_URL = "https://skillab-tracker.csd.auth.gr/api"

def login(username, password):
    url = f"{BASE_URL}/login"

    response = requests.post(url, json={"username": username, "password": password}, verify=False)
    response.raise_for_status()
    return response.json()

os.environ['API_TOKEN']= login(userdata.get("SKILLAB_USERNAME"), userdata.get("SKILLAB_PASSWORD"))

def auth_headers(token):
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type" : "application/x-www-form-urlencoded",
        "Accept": "application/json"
    }


def get_occupations(token, keywords=None, ancestors=None, keywords_logic="or"):
    url = f"{BASE_URL}/occupations"
    all_items = []
    page = 1
    page_size = 100
    payload = {}
    if keywords is not None:
        payload["keywords"] = keywords
        payload["keywords_logic"] = keywords_logic
    if ancestors is not None:
        payload["ancestors"] = ancestors

    print(payload)

    while True:
        params = {"page": page, "page_size": page_size}
        response_data = requests.post(url, params=params, data=payload, headers=auth_headers(token), verify=False).json()

        if not response_data.get('items'):
            break

        all_items.extend(response_data['items'])
        page += 1
    return {"count": len(all_items), "items": all_items}

# break an array into pieces
def chunked(iterable, size):
    for i in range(0, len(iterable), size):
        yield iterable[i:i + size]


def get_jobs(token, keywords, occupations_data, keywords_logic="or"):
    url = f"{BASE_URL}/jobs"
    jobs = {}

    page_size = 100
    CHUNK_SIZE = 25
    MAX_PAGES = 1000
    occupation_ids = list({occupation.get('id') for occupation in occupations_data.get('items')})

    for occ_chunk in chunked(occupation_ids, CHUNK_SIZE):
        page = 1

        while page <= MAX_PAGES:
            params = {"page": page, "page_size": page_size}
            payload = {"keywords": keywords, "keywords_logic": keywords_logic, "occupation_ids": occ_chunk}

            response = requests.post(
                url,
                params=params,
                data=payload,
                headers=auth_headers(token),
                verify=False
            )
            response.raise_for_status()
            data = response.json()

            items = data.get("items", [])
            if not items:
                break

            for job in items:
                jobs[job["id"]] = job

            page += 1

    return {
        "count": len(jobs),
        "items": list(jobs.values())
    }

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

# Searching for the agriculture related occupations using keywords

In [ ]:

keywords = ["agriculture", "agro-food",
                            "agronomy", "farming",
                            "horticulture", "livestock", "dairy",
                            "fisheries", "food processing", "crop management",
                            "sustainable agriculture", "organic farming" ]

if os.environ.get('API_TOKEN'):
    occupations_data = get_occupations(token=os.environ.get('API_TOKEN'), keywords=keywords)
    pprint(occupations_data)

else:
    print("Failed to obtain access token.")

{'keywords': ['agriculture', 'agro-food', 'agronomy', 'farming', 'horticulture', 'livestock', 'dairy', 'fisheries', 'food processing', 'crop management', 'sustainable agriculture', 'organic farming'], 'keywords_logic': 'or'}

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

{'count': 105,
 'items': [{'alternative_labels': ['fresh fish salesperson',
                                   'fish market salesperson',
                                   'fish and seafood specialized seller',
                                   'fresh seafood specialised seller',
                                   'fresh fish counter specialised seller',
                                   'fish stall specialised seller',
                                   'fish salesperson',
                                   'fresh fish specialised seller',
                                   'fresh seafood salesperson',
                                   'fish market specialised seller',
                                   'seafood specialised seller',
                                   'fisheries shop salesperson',
                                   'fresh fish shop salesperson',
                                   'seafood salesperson',
                                   'fish specialised seller',
                                   'fisheries salesperson',
                                   'fisheries shop specialised seller',
                                   'fisheries specialised seller',
                                   'fish stall salesperson',
                                   'fishmongers shop specialised seller'],
            'ancestors': [['http://data.europa.eu/esco/occupation/547b304b-9a72-4717-9b24-b7046df5f64e',
                           'http://data.europa.eu/esco/isco/C5223',
                           'http://data.europa.eu/esco/isco/C522',
                           'http://data.europa.eu/esco/isco/C52',
                           'http://data.europa.eu/esco/isco/C5']],
            'children': [],
            'description': 'Fish and seafood specialised sellers sell fish, '
                           'crustaceans and molluscs in specialised shops. \n'
                           '\xa0',
            'id': 'http://data.europa.eu/esco/occupation/062d666b-8b5f-4ff2-9047-113831eb3e9f',
            'label': 'fish and seafood specialised seller',
            'levels': [5]},
           {'alternative_labels': ['water-based fish farm technician',
                                   'water-based fisheries technician',
                                   'technician in water-based aquaculture'],
            'ancestors': [['http://data.europa.eu/esco/isco/C6221',
                           'http://data.europa.eu/esco/isco/C622',
                           'http://data.europa.eu/esco/isco/C62',
                           'http://data.europa.eu/esco/isco/C6']],
            'children': [],
            'description': 'Water-based aquaculture technicians coordinate and '
                           'supervise activities on fattening aquaculture '
                           'organisms in suspended systems (floating or '
                           'submerged structures). They participate in '
                           'extraction operations and handling organisms for '
                           'commercialisation. Water-based aquaculture '
                           'technicians\xa0supervise maintenance of equipment '
                           'and facilities (cages, rafts, longlines, bouchot).',
            'id': 'http://data.europa.eu/esco/occupation/0d6bb2cc-06b0-481c-b553-2a973be03254',
            'label': 'water-based aquaculture technician',
            'levels': [4]},
           {'alternative_labels': ['fisherman',
                                   'fishing vessel deckhand',
                                   'fisheries sailor',
                                   'trawlerman',
                                   'trawlerwoman',
                                   'fisherwoman'],
            'ancestors': [['http://data.europa.eu/esco/isco/C8350',
                           'http://data.europa.eu/esco/isco/C835',
                           'http://data.europa.eu/esco/isco/C83',
                           'http://data.europa.eu/esco/isco/C8']],
            'children': [],
            'description': 'Fisheries deckhands work on fishing vessels where '
                           'they carry out fishing related activities. They '
                           'undertake a wide range of fishing and maritime '
                           'work on land and at sea, such as handling of '
                           'fishing gears and catches, communications, supply, '
                           'seamanship, hospitality and stores.',
            'id': 'http://data.europa.eu/esco/occupation/18dafd4f-8c37-4276-b4b3-cfa31059b2b6',
            'label': 'fisheries deckhand',
            'levels': [4]},
           {'alternative_labels': ['berry picker',
                                   'flower picker',
                                   'fruit picker',
                                   'horticultural farm worker',
                                   'crop worker',
                                   'horticultural worker'],
            'ancestors': [['http://data.europa.eu/esco/isco/C9214',
                           'http://data.europa.eu/esco/isco/C921',
                           'http://data.europa.eu/esco/isco/C92',
                           'http://data.europa.eu/esco/isco/C9']],
            'children': [],
            'description': 'Horticulture workers carry out practical '
                           'activities and assist in\xa0nurseries or '
                           'greenhouses for the production of horticultural '
                           'crops.',
            'id': 'http://data.europa.eu/esco/occupation/1a9d99ba-4c08-4864-8f6a-1b0f2b4cf883',
            'label': 'horticulture worker',
            'levels': [4]},
           {'alternative_labels': ['crofter',
                                   'working farm manager',
                                   'smallholder'],
            'ancestors': [['http://data.europa.eu/esco/isco/C6130',
                           'http://data.europa.eu/esco/isco/C613',
                           'http://data.europa.eu/esco/isco/C61',
                           'http://data.europa.eu/esco/isco/C6']],
            'children': [],
            'description': 'Mixed farmers are responsible for managing all '
                           'aspects of livestock and crop production as a '
                           'small enterprise or for self-sufficiency.',
            'id': 'http://data.europa.eu/esco/occupation/1c1e86f9-6347-42d6-aa6e-c95b138bf640',
            'label': 'mixed farmer',
            'levels': [4]},
           {'alternative_labels': ['assistant in agricultural research',
                                   'bacteriological testing coordinator',
                                   'aquaculture technician',
                                   'biotechnician',
                                   'agricultural research assistant',
                                   'agricultural technologist',
                                   'horticultural technician',
                                   'viticulture technician'],
            'ancestors': [['http://data.europa.eu/esco/isco/C3142',
                           'http://data.europa.eu/esco/isco/C314',
                           'http://data.europa.eu/esco/isco/C31',
                           'http://data.europa.eu/esco/isco/C3']],
            'children': ['http://data.europa.eu/esco/occupation/ac036ea7-883a-4265-96d5-c02bbe6667e1',
                         'http://data.europa.eu/esco/occupation/b9e51ff4-d7fb-4653-bc72-65086ffc6e65',
                         'http://data.europa.eu/esco/occupation/f9cbdeb4-1559-4d45-b2d7-edf8aebe400b'],
            'description': 'Agricultural technicians collect and conduct '
                           'experiments and tests on agriculture and '
                           'aquaculture specimens. They provide support to '
                           'scientists and farmers and also analyse and report '
                           "on conditions in the collected specimens' "
                           'environments.',
            'id': 'http://data.europa.eu/esco/occupation/1f8314c2-01bd-4af4-babc-04d7034591b8',
            'label': 'agricultural technician',
            'levels': [4]},
           {'alternative_labels': ['local fisheries boatman',
                                   'fisheries boatwoman',
                                   'local fisheries boatwoman',
                                   'local boatman',
                                   'local fishing vessel skipper'],
            'ancestors': [['http://data.europa.eu/esco/isco/C6222',
                           'http://data.europa.eu/esco/isco/C622',
                           'http://data.europa.eu/esco/isco/C62',
                           'http://data.europa.eu/esco/isco/C6']],
            'children': [],
            'description': 'Fisheries boatmen operate small boats inshore and '
                           'near the coast only. They organise, manage and '
                           'execute shipping activities on deck and with '
                           'engines. Fisheries boatmen capture and conserve '
                           'fish or engage in aquaculture operations. They '
                           'respect the safety conditions and comply with '
                           'national and international regulations.',
            'id': 'http://data.europa.eu/esco/occupation/270528cf-2bf9-463d-aeaa-d169b1f767c1',
            'label': 'fisheries boatman',
            'levels': [4]},
           {'alternative_labels': ['flock manager',
                                   'sheep herder',
                                   'sheep flock manager',
                                   'sheep flock specialist',
                                   'flock movement specialist'],
            'ancestors': [['http://data.europa.eu/esco/isco/C6121',
                           'http://data.europa.eu/esco/isco/C612',
                           'http://data.europa.eu/esco/isco/C61',
                           'http://data.europa.eu/esco/isco/C6']],
            'children': [],
            'description': 'Shepherds manage the welfare and movement of '
                           'livestock, especially sheep, goats and other '
                           'grazing animals, in a variety of surroundings. \n',
            'id': 'http://data.europa.eu/esco/occupation/2a1190f0-14d5-4ce4-ade0-ef726a1887a0',
            'label': 'shepherd',
            'levels': [4]},
           {'alternative_labels': ['commodity dealer', 'commodities broker'],
            'ancestors': [['http://data.europa.eu/esco/isco/C3324',
                           'http://data.europa.eu/esco/isco/C332',
                           'http://data.europa.eu/esco/isco/C33',
                           'http://data.europa.eu/esco/isco/C3']],
            'children': ['http://data.europa.eu/esco/occupation/94adbb11-1c90-4092-ae91-781e8a55865d',
                         'http://data.europa.eu/esco/occupation/e40e4a07-4246-4c6f-a51c-89d35b6fe75e'],
            'description': 'Commodity brokers act as intermediary between '
                           'buyers and sellers of movable and immovable '
                           'property such as raw materials, livestock or real '
                           'estate. They negotiate prices and receive a '
                           'commission from the transactions. They research '
                           'market conditions for specific commodities in '
                           'order to inform their clients. They make bid '
                           'offers and calculate the cost of transactions.',
            'id': 'http://data.europa.eu/esco/occupation/2af80b12-a73a-4cc2-8af1-d26a1e60738d',
            'label': 'commodity broker',
            'levels': [4]},
           {'alternative_labels': ['senior crewwoman',
                                   'senior crewman',
                                   'bosum',
                                   'fisheries boatswain'],
            'ancestors': [['http://data.europa.eu/esco/isco/C8350',
                           'http://data.europa.eu/esco/isco/C835',
                           'http://data.europa.eu/esco/isco/C83',
                           'http://data.europa.eu/esco/isco/C8']],
            'children': [],
            'description': 'Boatswains organise the crew on deck and at the '
                           'fishing hold to execute the orders received from a '
                           'superior. They coordinate the operations of '
                           'maintenance, manoeuvres, assembly and repair of '
                           'fishing gear and sorting, processing and '
                           'preserving of the catches while observing the '
                           'hygienic standards and established safety '
                           'regulations.',
            'id': 'http://data.europa.eu/esco/occupation/2e46a2a3-4d33-469e-8d50-588cc17e6bed',
            'label': 'boatswain',
            'levels': [4]},
           {'alternative_labels': ['fish farm cage mooring worker',
                                   'fisheries cage mooring worker',
                                   'fish cage mooring worker'],
            'ancestors': [['http://data.europa.eu/esco/isco/C9216',
                           'http://data.europa.eu/esco/isco/C921',
                           'http://data.europa.eu/esco/isco/C92',
                           'http://data.europa.eu/esco/isco/C9']],
            'children': [],
            'description': 'Aquaculture cage mooring workers operate '
                           'highly-specialised equipment in order to moor '
                           'cages in stable stations, drifting cages or even '
                           'self-propelled and semi-submerged cages.\xa0',
            'id': 'http://data.europa.eu/esco/occupation/2e4b41dd-b63d-403d-a0ad-dd323cd3ddac',
            'label': 'aquaculture cage mooring worker',
            'levels': [4]},
           {'alternative_labels': ['farming operations manager',
                                   'farmer',
                                   'agricultural operations manager',
                                   'agricultural manager'],
            'ancestors': [['http://data.europa.eu/esco/isco/C6130',
                           'http://data.europa.eu/esco/isco/C613',
                           'http://data.europa.eu/esco/isco/C61',
                           'http://data.europa.eu/esco/isco/C6']],
            'children': [],
            'description': 'Farm managers plan and organise the daily '
                           'operations, resourcing and business management of '
                           'animal and crops producing farms.',
            'id': 'http://data.europa.eu/esco/occupation/4552095e-3396-4831-86ad-4fc34ec39a19',
            'label': 'farm manager',
            'levels': [4]},
           {'alternative_labels': ['fisheries refrigerating engineer',
                                   'fishery refrigeration engineer',
                                   'engineer in fisheries refrigeration',
                                   'fishing vessel refrigeration engineer',
                                   'fishing boat freezer engineer',
                                   'fisheries refrigeration and power engineer',
                                   'fisheries refrigeration technician',
                                   'fishing boat refrigeration engineer',
                                   'fisheries electrician',
                                   'fisheries cold storage engineer',
                                   'fisheries refrigeration engineering expert',
                                   'fisheries refrigeration engineer',
                                   'fisheries refrigeration engineering '
                                   'adviser',
                                   'fisheries refrigeration engineering '
                                   'consultant',
                                   'refrigeration plant engineer',
                                   'fisheries electrician and refrigeration '
                                   'engineer',
                                   'fisheries refrigeration engineering '
                                   'specialist',
                                   'fishing vessel freezer engineer'],
            'ancestors': [['http://data.europa.eu/esco/isco/C3151',
                           'http://data.europa.eu/esco/isco/C315',
                           'http://data.europa.eu/esco/isco/C31',
                           'http://data.europa.eu/esco/isco/C3']],
            'children': [],
            'description': 'Fisheries engineering technicians perform '
                           'maintenance and repair machines and equipment in '
                           'the fish hold and refrigeration system on board of '
                           'fishing vessels.',
            'id': 'http://data.europa.eu/esco/occupation/340b04fd-6312-47e5-80ff-28222a343864',
            'label': 'fisheries engineering technician',
            'levels': [4]},
           {'alternative_labels': ['marine fisheries consultant',
                                   'senior fisheries specialist',
                                   'senior fisheries biologist',
                                   'fisheries scientist',
                                   'fisheries specialist',
                                   'marine fisheries scientist',
                                   'fisheries consultant',
                                   'marine fisheries adviser',
                                   'marine fisheries biologist',
                                   'fisheries biologist',
                                   'fisheries sustainability consultant'],
            'ancestors': [['http://data.europa.eu/esco/isco/C2132',
                           'http://data.europa.eu/esco/isco/C213',
                           'http://data.europa.eu/esco/isco/C21',
                           'http://data.europa.eu/esco/isco/C2']],
            'children': [],
            'description': 'Fisheries advisers provide consultancy on fish '
                           'stocks and their habitats. They manage the costal '
                           'fishing business modernisation and provide '
                           'improvement solutions. Fisheries advisers develop '
                           'plans and policies for fisheries management. They '
                           'may provide advice on protected farms and wild '
                           'fish stock.',
            'id': 'http://data.europa.eu/esco/occupation/3b018148-8e92-4177-9267-5f090386f6a3',
            'label': 'fisheries adviser',
            'levels': [4]},
           {'alternative_labels': ['fish stall manager',
                                   'fisheries store manager',
                                   'fresh fish counter manager',
                                   'fresh seafood shop manager',
                                   'fish market sales manager',
                                   'fisheries shop manager',
                                   'fish shop manager',
                                   'fishmongers shop manager',
                                   'seafood shop manager'],
            'ancestors': [['http://data.europa.eu/esco/occupation/9e81adde-9983-44fa-b74b-c548d0dbfbdd',
                           'http://data.europa.eu/esco/isco/C1420',
                           'http://data.europa.eu/esco/isco/C142',
                           'http://data.europa.eu/esco/isco/C14',
                           'http://data.europa.eu/esco/isco/C1']],
            'children': [],
            'description': 'Fish and seafood shop managers assume '
                           'responsibility for activities and staff in '

we notice that the occupations that are returned belong to different ISCO categories, not only to ISCO category 6, which is for Skilled Agricultural, Forestry and Fishery Workers. Nevertheless, many of them are relevant. For example, we get an occupation with the label 'livestock worker', which is relevant. This belongs to ISCO category 9 (Elementary Occupations).

So our next step is to search for any category related specifically to Agriculture in the ISCO classification. We use the tables at: https://ilostat.ilo.org/methods/concepts-and-definitions/classification-occupation/ for that matter.

The categories that we found are the following:

| ISCO code | Description |
| --------- | ----------- |
| 131 | Production Managers in Agriculture, Forestry and Fisheries |
| 2131 | Biologists, Botanists, Zoologists and Related Professionals |
| 2132 | Farming, Forestry and Fisheries Advisers |
| 3142 | Agricultural Technicians |
| 6 | Skilled Agricultural, Forestry and Fishery Workers |
| 7233 | Agricultural and Industrial Machinery Mechanics and Repairers |
| 816 | Food and Related Products Machine Operators |
| 92 |  Agricultural, Forestry and Fishery Labourers |


Intentionally, we are very specific on some categories, and more broad on some others. This is because category 6 is dedicated to Agricultural Workers, so we can take all the occupations and exclude manually what is irrelevant. On the contrary, categories like 2 (Professionals) are too generic to take all the occupations, so we focus only on the more specific sub-categories.

In any case, we can manually add or exclude occupations based on the relevance of the results.

# Extraction of agriculture related occupations

We are now going to find all the occupations that have the above ISCO categories as ancestors.

In [ ]:
ancestors = [ 'http://data.europa.eu/esco/isco/C131',


              'http://data.europa.eu/esco/isco/C3142',
              'http://data.europa.eu/esco/isco/C6',
              'http://data.europa.eu/esco/isco/C7233',
              'http://data.europa.eu/esco/isco/C816',
              'http://data.europa.eu/esco/isco/C92']

if os.environ.get('API_TOKEN'):
    occupations_data = get_occupations(token=os.environ.get('API_TOKEN'), ancestors=ancestors)
    for occupation in occupations_data['items']:
        print(occupation.get('label'))
    print(len(occupations_data['items']))
    #pprint(occupations_data)

else:
    print("Failed to obtain access token.")

{'ancestors': ['http://data.europa.eu/esco/isco/C131', 'http://data.europa.eu/esco/isco/C2131', 'http://data.europa.eu/esco/isco/C2132', 'http://data.europa.eu/esco/isco/C3142', 'http://data.europa.eu/esco/isco/C6', 'http://data.europa.eu/esco/isco/C7233', 'http://data.europa.eu/esco/isco/C816', 'http://data.europa.eu/esco/isco/C92']}

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

hydrogenation machine operator
pasta operator
coffee grinder
land-based machinery technician
bee breeder
aquaculture hatchery manager
fluid power technician
water-based aquaculture technician
fur animals breeder
candy machine operator
pharmacologist
chilling operator
blending plant operator
horse breeder
sauce production operator
tree surgeon
biophysicist
horticulture worker
crop production manager
mixed farmer
brew house operator
agricultural technician
vineyard machinery operator
on foot aquatic resources collector
vineyard supervisor
greaser
rotating equipment mechanic
deep-sea fishery worker
physiologist
industrial machinery mechanic
fisheries boatman
centrifuge operator
shepherd
textile machinery technician
aquaculture cage mooring worker
farm manager
aquaculture cage technician
sugar refinery operator
cocoa press operator
coffee roaster
fruit and vegetable picker
starch converting operator
fisheries adviser
kettle tender
forestry adviser
cellar operator
toxicologist
aquaculture harvesting manager
cacao beans cleaner
pneumatic systems technician
botanist
equine yard manager
aquaculture production manager
forge equipment technician
fruit production team leader
moulding machine technician
baking operator
marine fitter
geneticist
clarifier
livestock worker
blender operator
equine worker
cacao bean roaster
honey extractor
bioinformatics scientist
aquaculture biologist
food biotechnologist
fisheries assistant engineer
biochemist
carbonation operator
blanching operator
fish canning operator
fruit-press operator
malt kiln operator
forest worker
extract mixer tester
distillery miller
animal behaviourist
beverage filtration technician
aquaculture rearing technician
dryer attendant
poultry sexer
fish production operator
aquaculture husbandry manager
prepared meat operator
dairy products manufacturing worker
marine mechanic
vineyard manager
horticulture production team leader
starch extraction operator
mining equipment mechanic
distillery worker
interior landscaper
fat-purification worker
dairy processing operator
garden labourer
catcher
aquaculture recirculation manager
groundsman/groundswoman
hop farmer
microbiologist
aquaculture hatchery worker
water-based aquaculture worker
aquaculture site supervisor
germination operator
wine fermenter
construction equipment technician
sheep breeder
cattle breeder
immunologist
milk heat treatment process operator
epidemiologist
arboriculturist
animal feed operator
viticulture adviser
fisheries master
yeast distiller
groom
aquaculture husbandry worker
agricultural scientist
vineyard cellar master
agronomist
botanicals specialist
hunter
crop production worker
vermouth manufacturer
curator of horticulture
crane technician
poultry breeder
horticulture production manager
chocolate moulding operator
aquaculture mooring manager
aquaculture harvesting technician
agronomic crop production team leader
miller
fruit and vegetable canner
aquaculture husbandry technician
cocoa mill operator
liquor grinding mill operator
livestock advisor
cider fermentation operator
food production operator
vineyard worker
landscape gardener
aquaculture hatchery technician
animal feed nutritionist
pig breeder
aquaculture recirculation technician
cigarette making machine operator
refining machine operator
biologist
aquaculture quality supervisor
marine biologist
forester
forest ranger
forestry machinery technician
liquor blender
flour purifier operator
bulk filler
agricultural machinery technician
aquaculture harvesting worker
fisheries boatmaster
Agricultural and forestry production managers
Aquaculture and fisheries production managers
Market-oriented skilled agricultural workers
Subsistence livestock farmers
Market gardeners and crop growers
Field crop and vegetable growers
Tree and shrub crop growers
Gardeners, horticultural and nursery growers
Mixed crop growers
Animal producers
Livestock and dairy producers
Poultry producers
Apiarists and sericulturists
Animal producers not elsewhere classified
Mixed crop and animal producers
Mixed crop and animal producers
Market-oriented skilled forestry, fishery and hunting workers
Forestry and related workers
Forestry and related workers
Fishery workers, hunters and trappers
Aquaculture workers
Inland and coastal waters fishery workers
Deep-sea fishery workers
Hunters and trappers
Subsistence farmers, fishers, hunters and gatherers
Subsistence crop farmers
Subsistence crop farmers
Subsistence livestock farmers
Subsistence mixed crop and livestock farmers
Subsistence mixed crop and livestock farmers
Subsistence fishers, hunters, trappers and gatherers
Subsistence fishers, hunters, trappers and gatherers
Food and related products machine operators
Agricultural, forestry and fishery labourers
Crop farm labourers
Livestock farm labourers
Mixed crop and livestock farm labourers
Garden and horticultural labourers
Forestry labourers
Fishery and aquaculture labourers
203

# Limiting the results

We notice that using the above keywords, although the results are importantly limited, some of the job offers that are found are not significantly relevant to agriculture.

It is important that we keep only the agriculture related jobs, so that out data is accurate and worthy of analysis.


## Method

To face the above problem, we will reduce the ESCO categories used as parameters. In addition, we will perform multiple searches with different keywords each time. All the retrieved items (job items) will be stored in a dictionnary with the job id as the id.

Finally, we will perform manual removal of any job offer that is not related to agriculture.

We understand that this could potentially exclude some of the job offers, even some that are actually relevant to agriculture. Nevertheless, as thousands of job offers exist, we consider that the final statistical outcome is accurate.

We will modify our methods if needed.

## Modifications

From the ISCO table used previously, decided to exclude:

- 2131: Biologists, Botanists, Zoologists and Related Professionals

  It is too broad and specialized in a medical way, it contains skills that are not relevant or not necessary for an agriculture-related profession

- 7233: Agricultural and Industrial Machinery Mechanics and Repairers

  It concernes mechanics and agricultural staff/managers. Also, it concerns industrial machinery in general so it is also too broad.

-  816: Food and Related Products Machine Operators

Therefore, the categories we are eventually using are the following:


| ISCO code | Description |
| --------- | ----------- |
| 131 | Production Managers in Agriculture, Forestry and Fisheries |
| 2132 | Farming, Forestry and Fisheries Advisers |
| 3142 | Agricultural Technicians |
| 6 | Skilled Agricultural, Forestry and Fishery Workers |
| 92 |  Agricultural, Forestry and Fishery Labourers |

In addition, we will perform multiple searches

Getting the skills found in the job offers

In [ ]:
ancestors = [ 'http://data.europa.eu/esco/isco/C131',
            'http://data.europa.eu/esco/isco/C2132',
            'http://data.europa.eu/esco/isco/C3142',
            'http://data.europa.eu/esco/isco/C6',
            'http://data.europa.eu/esco/isco/C92']

#ancestors = ['http://data.europa.eu/esco/isco/C92']

if os.environ.get('API_TOKEN'):
    occupations_data = get_occupations(os.environ.get('API_TOKEN'), ancestors=ancestors)
    for occupation in occupations_data['items']:
        print(occupation.get('label'))
    print(len(occupations_data['items']))
    #pprint(occupations_data)

else:
    print("Failed to obtain access token.")

{'ancestors': ['http://data.europa.eu/esco/isco/C131', 'http://data.europa.eu/esco/isco/C2132', 'http://data.europa.eu/esco/isco/C3142', 'http://data.europa.eu/esco/isco/C6', 'http://data.europa.eu/esco/isco/C92']}

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

bee breeder
aquaculture hatchery manager
water-based aquaculture technician
fur animals breeder
horse breeder
tree surgeon
horticulture worker
crop production manager
mixed farmer
agricultural technician
vineyard machinery operator
on foot aquatic resources collector
vineyard supervisor
deep-sea fishery worker
fisheries boatman
shepherd
aquaculture cage mooring worker
farm manager
aquaculture cage technician
fruit and vegetable picker
fisheries adviser
forestry adviser
aquaculture harvesting manager
equine yard manager
aquaculture production manager
fruit production team leader
livestock worker
equine worker
forest worker
aquaculture rearing technician
poultry sexer
aquaculture husbandry manager
vineyard manager
horticulture production team leader
interior landscaper
garden labourer
catcher
aquaculture recirculation manager
groundsman/groundswoman
hop farmer
aquaculture hatchery worker
water-based aquaculture worker
aquaculture site supervisor
sheep breeder
cattle breeder
arboriculturist
viticulture adviser
fisheries master
groom
aquaculture husbandry worker
agricultural scientist
vineyard cellar master
agronomist
hunter
crop production worker
poultry breeder
horticulture production manager
aquaculture mooring manager
aquaculture harvesting technician
agronomic crop production team leader
aquaculture husbandry technician
livestock advisor
vineyard worker
landscape gardener
aquaculture hatchery technician
pig breeder
aquaculture recirculation technician
aquaculture quality supervisor
forester
forest ranger
aquaculture harvesting worker
fisheries boatmaster
Agricultural and forestry production managers
Aquaculture and fisheries production managers
Market-oriented skilled agricultural workers
Subsistence livestock farmers
Market gardeners and crop growers
Field crop and vegetable growers
Tree and shrub crop growers
Gardeners, horticultural and nursery growers
Mixed crop growers
Animal producers
Livestock and dairy producers
Poultry producers
Apiarists and sericulturists
Animal producers not elsewhere classified
Mixed crop and animal producers
Mixed crop and animal producers
Market-oriented skilled forestry, fishery and hunting workers
Forestry and related workers
Forestry and related workers
Fishery workers, hunters and trappers
Aquaculture workers
Inland and coastal waters fishery workers
Deep-sea fishery workers
Hunters and trappers
Subsistence farmers, fishers, hunters and gatherers
Subsistence crop farmers
Subsistence crop farmers
Subsistence livestock farmers
Subsistence mixed crop and livestock farmers
Subsistence mixed crop and livestock farmers
Subsistence fishers, hunters, trappers and gatherers
Subsistence fishers, hunters, trappers and gatherers
Agricultural, forestry and fishery labourers
Crop farm labourers
Livestock farm labourers
Mixed crop and livestock farm labourers
Garden and horticultural labourers
Forestry labourers
Fishery and aquaculture labourers
111

We now get 111 occupations, before it was 203

# Keywords based on litterature's thematic map by Bibliometrix

In [ ]:
justified_keywords = [
    "agricultural management",
    "farm management",
    "crop management"
    "sustainable agriculture",
    "food security",
    "biodiversity",
    "cropping systems",
    "land-use",
    "crop production",
    "conservation agriculture",
    "farming systems",
    "irrigation strategies",
    "manage livestock",
    "soil fertility",
    "agroecology",
    "soil organic matter",
    "water management",
    "soil health",
    "tillage",
    "no-tillage",
    "crop resilience",
    "crop yield",
    "deficit irrigation",
    "nitrogren use efficiency",
    "water productivity",
    "fertilizer use",
    "drip irrigation",
    "precision agriculture",
    "precision farming",
    "agriculture remote sensing",
    "smart agriculture",
    "crop disease",
    "pest management",
    "weed detection",
    "grain yield",
    "efficient water use",
    "animal breeding",
    "biofortification",
    "crop improvement",
    "plant breeding",
    "powdery mildew",
    "integrated pest management",
    "biological control",
    "weed management",
    "use pesticides",
    "integrated weed management",
    "crop protection"
]

print(len(justified_keywords))

46

In [ ]:

jobs_data = get_jobs(os.environ.get('API_TOKEN'), justified_keywords, occupations_data, "or")
# pprint(jobs_data)
for job in jobs_data['items']:
    print(job.get('title'))
print(f"successful access to jobs data - count: {jobs_data.get("count")}")

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'skillab-tracker.csd.auth.gr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

MANAGER OF PRODUCTION
Agricultural Sales - Export Managers
Farm Veterinarian
Veterinary
Senior Consultant Agriculture and Food Sector F/M
DIGITAL TRANSFORMATION INNOVATION PROJECT MANAGER M/F
Technical Leader in boilermaking H/F
Sales consultant (m/f/d) agricultural and construction machinery
Production Team Leader 3*8 M/F
Responsable QSE H/F
Agro Logistics Manager M/F
Agro Logistics Manager
Agricultural workshop manager
Agricultural mechanic M/F
Versatile agricultural worker M/F
Poultry worker M/F
Poultry worker M/F
Landscape gardener M/F
Agricultural Technician M/F
Land and Agricultural Estate Operations Director M/F
Security Facilitator M/F
Water Operations Technician M/F
Day Maintenance Technician M/F
Maintenance and New Works Technician M/F
After-sales team leader M/F
Technician, Animal Research Facility [LKCMedicine]
Technician, Animal Research Facility [LKCMedicine]
LABORATORY ANIMAL
LABORATORY ANIMAL
Sales Representative
WAREHOUSE & CUSTOMER MANAGEMENT OFFICER (FARMER / FOOD TECHNOLOGIST)
Agronomic R&D Technician | Agronomist
Agronomic R&D Technician | Agronomist
Agronomic R&D Technician | Agronomist
digital domain manager F/M
Sales Engineer - Heat Pumps M/F
Director of Poultry Operations M/F
Agronomic R&D Technician | Agronomist
Food Quality and Safety System Manager M/F
Poultry Sales Director M/F
Day Maintenance Technician M/F
Head of the Digital Product Development Department M/F
Subsidiary Manager M/F
Subsidiary Manager M/F
Poultry Sales Director M/F
Versatile agricultural worker M/F
Industrial maintenance technician M/F Domaine Avicole
Chauffeur SPL* H/F
Poultry worker M/F
Technical IT Project Manager M/F
Technical IT Project Manager M/F
Agricultural mechanic M/F
Water Operations Technician M/F
Land and Agricultural Estate Operations Director M/F
Sole Accountant M/F
Day Maintenance Technician M/F
Head of culture M/F
Infrastructure Project Manager M/F
Infrastructure Project Manager M/F
Head of the Sanitation Maintenance Department M/F
Day Maintenance Technician M/F
Station Manager
Sales Engineer - Heat Pumps M/F
Production Team Leader 3*8 M/F
Veterinarian | Scientific Officer
Plant Innovation Manager F/M
Versatile agricultural worker - Animal worker M/F
Workshop Manager 3*8 M/F
Day Maintenance Technician M/F
After-sales service team leader M/F
Poultry worker M/F
Chauffeur SPL* H/F
Head of the Digital Product Development Department M/F
Subsidiary Manager M/F
Subsidiary Manager M/F
Poultry Sales Director M/F
Food Quality and Safety System Manager M/F
Data Scientist Agronome H/F
Day Maintenance Technician M/F
Advisor with a focus on robust primary production within Greppa Näringen
Doctoral student in beef production on natural pastures
Sales manager north, Väktodling
Researchers - bioinformatics and adaptation of crops to climate change
Technician for the VA unit
Deputy store manager 100% to Örebro
Expert/project manager in milk for sustainable animal production
Naturbrukskolan Uddetorp is looking for agricultural operations personnel
Researchers with a focus on advanced analysis of fish behavior
Trial & Project Manager
Bath water technician for new assignment in Täby
Veterinarian with an interest in infectious diseases in poultry
Veterinarian with an interest in infectious diseases in poultry
Trial & Project Manager
Contingency manager with a focus on project management
Administrators and advisors with a focus on farm animals
Contingency manager with a focus on the development of forms of support
Contingency manager with a focus on project management
Post-doc position on the quality of the dead wood and dead-wood dependent organisms
Postdoc position in deadwood quality and saproxylic communities
Teacher in agricultural subjects - Komvux
Agricultural adviser to the Councilors in Sjuhärad
Business manager for the new center for sustainable primary production
Project manager fisheries management
Secondary school teacher in agriculture - temporary position
Farm worker/excavator
Supervisor for production
Summer job 2025;     Tractor driver for Widegrens Gård on Gotland
Tractor and machine operator for Widegrens Gård on Gotland
Professor in Business Studies
Operating technician for the Swedish Tourist Association's property department in Norrb...
Postdoc in agricultural water management
Doctoral position in modeling of plant-environment and plant-plant interactions
PhD in modelling plant-environment and plant-plant interactions
Committed and relationship-building production manager for Sydvatten
Water Equipment Maintenance Technician M/F
Responsable des Opérations H/F
Animal care employee or animal care assistant (f/m/d)
University lecturer in plant ecology
Senior Lecturer/Associate Professor* in Plant Ecology
Development leader within Community Building
Doctoral student, Biology - plant pathology and resistance breeding
PhD student, Biology - Plant Pathology and Resistance Breeding
Acting supervisor in animal welfare
Syngenta Group China Scientist
Animal welfare officer
Animal welfare officer
Researcher in Bioinformatics and crop adaptation to climate change
Senior Scientist with background in farm animal genetics
Contingency manager with a focus on the development of forms of support
MARKETING MANAGER FOR KONVEX AB
Senior Consultant Agriculture and Food Sector F/M
DIGITAL TRANSFORMATION INNOVATION PROJECT MANAGER M/F
Technical Leader in boilermaking H/F
digital domain manager F/M
Technical IT Project Manager M/F
Infrastructure Project Manager M/F
Plant Innovation Manager F/M
Advisor with a focus on robust primary production within Greppa Näringen
Doctoral student in beef production on natural pastures
Sales manager north, Väktodling
Researchers - bioinformatics and adaptation of crops to climate change
Technician for the VA unit
Deputy store manager 100% to Örebro
Expert/project manager in milk for sustainable animal production
Naturbrukskolan Uddetorp is looking for agricultural operations personnel
Researchers with a focus on advanced analysis of fish behavior
Trial & Project Manager
Bath water technician for new assignment in Täby
Veterinarian with an interest in infectious diseases in poultry
Veterinarian with an interest in infectious diseases in poultry
Trial & Project Manager
Contingency manager with a focus on project management
Administrators and advisors with a focus on farm animals
Contingency manager with a focus on the development of forms of support
Contingency manager with a focus on project management
Post-doc position on the quality of the dead wood and dead-wood dependent organisms
Postdoc position in deadwood quality and saproxylic communities
Teacher in agricultural subjects - Komvux
Agricultural adviser to the Councilors in Sjuhärad
Business manager for the new center for sustainable primary production
Project manager fisheries management
Secondary school teacher in agriculture - temporary position
Farm worker/excavator
Supervisor for production
Summer Job 2025;     Tractor Driver For Widegrens Gård On Gotland
Tractor and Machine Operator for Widegrens Gård on Gotland
Professor in Business Studies
Operating technician for the Swedish Tourist Association's property department in Norrb...
Postdoc in agricultural water management
Doctoral position in modeling of plant-environment and plant-plant interactions
PhD in modelling plant-environment and plant-plant interactions
University lecturer in plant ecology
Senior Lecturer/Associate Professor* in Plant Ecology
Development leader within Community Building
Doctoral student, Biology - plant pathology and resistance breeding
PhD student, Biology - Plant Pathology and Resistance Breeding
Acting supervisor in animal welfare
Syngenta Group China Scientist
Animal welfare officer
Animal welfare officer
Researcher in Bioinformatics and crop adaptation to climate change
Senior Scientist with background in farm animal genetics
Contingency manager with a focus on the development of forms of support
MARKETING MANAGER FOR KONVEX AB
PLANT PRODUCTION FARMER (XANTHI)
Training to become a cattle farming specialist (m/f/d)
Technical assistant (m/f/d) breeding garden
Technical Support Engineer
Application expert
Operations manager SLU Lanna Property
Naturbrukskolan Uddetorp is looking for a special teacher in mathematics
Substitute Cultivation coordinator/project manager
Naturbrukskolan Uddetorp is looking for agricultural operations personnel
Administrator for the Ministry of Rural Affairs and Infrastructure
Researchers, Effect of temperature-induced germ line determination in plants
Work with plant protection - three services in our socially important business
Animal welfare officer
Agricultural adviser to the Councilors in Sjuhärad
Naturbrukskolan Uddetorp is looking for a cook
Plant cultivation advisor to the Housekeeping Society Kalmar Kronoberg Blekinge
Coordinating Production Manager
Technicien Maintenance Itinérant H/F
Chef d'Equipe H/F
Scientist in plant molecular biology and genetics
Natural School Uddetorp is looking for two student coaches
Plant cultivation adviser to the Housekeeping Society Kalmar Kronoberg Blekinge
Technicien Exploitation Eau H/F
Biträdande rektor till Munkagårdsgymnasiet
Badvattentekniker till nytt uppdrag i Täby
Kundansvarig till Biototal Group i Skåne
Γεωπόνους Πωλήσεων - Export Managers
Besiktningstekniker
Besiktningstekniker
Arbeta med att stärka krisberedskapen inom djurområdet
Forskare
DSS eller veterinär med chefsuppdrag för operationsenheten
Kundansvarig till Biototal med arbetsområde Gävle med omnejd
Forskare, laboratoriestudier på torvjord
Responsable de pôle installation en agriculture (F/H)
Herdenmanager m/w/d
Gärtner*in (m/w/d) mit Fachrichtung Gemüsebau
Säljande avelsrådgivare
Djurskyddshandläggare med fokus på lantbrukets djur
MASTER THESIS Land management practices for FLAG emissions reduction and removals increase
Enhetschef till enheten för landsbygdsutveckling
Stalltekniker
Postdoc - Plant breeding towards nutritional quality in cereals
Postdoktor i biologi med fokus på fiskekologi och hydrologi
Butiks- och reservdelssäljare
Elevassistent
Vi söker lantbruksekonomer och redovisningskonsulter
Chef till Landsbygdsavdelningen, Funktionen för Djurskydd
Researcher Rural Development
Parkingenjör till Parkenheten
Djurvårdare/DSS/Veterinär med chefsuppdrag för vård-och operationsenheten
Butiks- och reservdelssäljare
Butiks- och reservdelssäljare
Växtodlingssäljare
Magasinier H/F
Postdoktor i akvatisk ekologi
Tekniker
Doktorand inom växtbiologi med fokus på cellväggens dynamik
Stadsbonde för kunskapshöjande odling inom staden
Chef Samhällsbyggnadsserviceförvaltningen
Produktadministratör
Skiftledare till produktionen
Djurskyddshandläggare
Vikarie Djurskötare
Badvattentekniker till nytt uppdrag i Täby
Chef de Projet Infrastructure H/F
Agraringenieur/ Anbauberater (m/w/d)
Försökstekniker
Produktionsledare/Driftledare med inriktning dikor och växtodling Svartsjö
INKÖPARE GRIS TILL SKÖVDE SLAKTERI
Universitetslektor i skogspatologi
Senior Lecturer (Associate Professor) in Forest Pathology
Vi söker lantbruksekonomer och redovisningskonsulter
Badvattentekniker till nytt uppdrag i Täby
Βοηθός Παραγωγής Καλλωπιστικών Φυτών
Agronomic R&D Researcher | Γεωπόνος
Agronomic R&D Researcher | Γεωπόνος
Chef de Projet Infrastructure H/F
Secodi Technicien itinérant H/F
Sachbearbeiter im Grunderwerb (w/m/d)
Technicien de Maintenance 3x8 H/F
Study Director /undersökningsledare
BMA med uppdrag som enhetschef för Klinisk kemiska laboratoriet, SLU
Assistent till Kriscentrums skyddade boenden
Doktorand i vattenkraftens påverkan på sjöars funktion och diversitet
Forskningsassistent
Berga söker en driftig växtodlings lärare
Kvalitetsansvarig Jord - Forma framtidens hållbara jordproduktion med oss!
Naturbrukslärare Växtodling
Rådgivare inom växtodling till kunskapsnav miljö och klimat
Postdoktor: Växthusgasutsläpp från jordar och metoder för att minska dem
Study Director /undersökningsledare
Länsveterinär till Länsstyrelsen Gävleborg
Post doc  Mapping aquatic resources in a changing climate
Biolog
Trädgårdsmästare
Amanuens
Fastighetsskötare vid Institutionen för akvatiska resurser
Technical Sales Representative
Pedagog till S:t Hansgården
Fiskehandläggare
Systemspecialist / Teknisk dokumenthantering till Stockholm
Utredare Havsplanering Konsekvensbedömning
Senior Data Sustainability Specialist - Viby, Stockholm, Düsseldorf, Nijkerk or Remote
Vi söker växtodlingsrådgivare till växtskyddscentralen i Landskrona
Handläggare för restaurering av vatten- och våtmarksmiljöer
ΓΕΩΠΟΝΟΣ ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ (ΞΑΝΘΗ)
Agronomic R&D Specialist| Γεωπόνος - Λάρισα
Agronomic R&D Specialist | Γεωπόνος
Kundansvarig Uppsala
Kundansvarig till Biototal Group i Skåne
Laboratoriechef vid institutionen för mark och miljö
Agronomist
AnimalOOO söker en UI/UX designer
Driftschef
Regional åtgärdssamordnare för fysiska åtgärder
Forskningsassistent
Study Director /undersökningsledare
Växtodlingsrådgivare Dalarna
Professor of Bioinformatics
ΓΕΩΠΟΝΟΣ ΣΤΕΛΕΧΟΣ ΠΩΛΗΣΕΩΝ B2B
ΓΕΩΠΟΝΟΣ ΠΩΛΗΤΗΣ
CTO / Tech lead (H/F) REF 8209-JE
Butiks- och reservdelssäljare
Traktorförare Säsong 2025
Vattenrådgivare
Badvattentekniker till nytt uppdrag i Täby
Regionchef
Djurskötare mjölkproduktion
Driftledare Växtodling
Naturbruksskolan Sötåsen söker vikarierande lärare i svenska och engelska
PhD in Aquatic Ecology: Hydropower impacts on lake function & biodiversity
Εργασία σε Παραγωγή Καλλωπιστικών Φυτών
Business Analyst
MDM Developer | HT2025PM0106
Mécanicien agricole H/F
Maraîcher H/F
Sales intern (praktikant)
Agronom/ biolog med fokus på kvalitetsstyrning (kvalitetskoordinator)
LANTBRUKSARBETARE - VISLANDA
Medarbetare till enheten för jordbruk och livsmedelsföretagande
Medarbetare till enheten för jordbruk och livsmedelsföretagande
Postdoctoral researcher in dairy cattle grazing
Fritidskonsulent Fiske, Fritid
Senior Lecturer in Chemical Ecology with a focus on Disease Vectors
Vattenrådgivare
Postdoktor - tillväxt och försvar hos Brassica napus
Trädgård och markskötsel på AstraZeneca i Mölndal
Förman Mjölkproduktion
Varmköks ansvarig till butiksköket
Utredare, inriktning  ekonomisk modellering och miljöeffekter av pesticider
Traktorförare Säsong 2025
Professor i One Health med inriktning livsmedelsproduktion
Naturbruksskolan Sötåsen söker vikarierande lärare i svenska och historia
Πρακτική άσκηση Γεωπονίας
ERP Data Analyst & Reporting Specialist
ENSEIGNANT-CHERCHEUR EN GEO DATA SCIENCE (F/H)
Work Force Management Senior Manager - H/F
Enhetschef, skydd och utveckling, Natur- och vattenavdelningen
Internrevisor för IP Sigill Frukt & Grönt sökes till Toppfrys
Postdoc - data-driven approaches for improved crop protection
Enhetschef, skydd och utveckling, Natur- och vattenavdelningen
Djurskyddshandläggare
Sandvikengården söker en biträdande Gårdsföreståndare
Postdoktor - data-drivna metoder för förbättrat växtskydd
One postdoc - multifunctionality of diversified agroecosystems
Grönyteskötare till uppdrag i Staffanstorp
Grönyteskötare till uppdrag i Lund
Grönyteskötare till uppdrag i Lomma
Grönyteskötare till uppdrag i Burlöv kommun
Säsongsarbetare till Vattenenheten
Handläggare med ansvar för jakt- och viltvårdsfrågor
Vi söker två agronomer eller lantmästare med jordbruksföretaget i fokus
KMA-koordinator - Göteborg
Forskande veterinär med hästkompetens sökes!
Växtodlingsrådgivare
Professor of One Health with focus on food production
Naturbruksskolan Sötåsen söker lärare matematik/speciallärare
Agronomic R&D Specialist| Γεωπόνος - Κρήτη
Horticultural Specialist till Swegreen
Rector of Forslundagymnasiet
Natural technician for the nature conservation unit
Production controller
Head of Department Nature and Water Department
Manager to the dog section Swedec
Lageransvarig Victorsson Poultry AB
Financial administrator, LTV Faculty's Office
Operating technician to Häggeberg's waterworks
Operating technicians VA
PhD Student in Plant Genetics and Breeding
Officer Fisheries follow -up unit
Animal Technician to AZ in Gothenburg
Green Superior to assignments in Burlöv Municipality
Nursery school to Billbäcks Nursery
Greenish coaches for assignments in Lomma
GreenThe coach to assignment in Staffanstorp
PhD Position in Disease and Restoration Ecology
Marketing managers to department in agriculture, food and cycle technology
Doctoral student in disease and restoration ecology
Natural School Sweet Seeks Teacher Mathematics
Animal caretakers with cousin competence
Investigator The Field Control Unit
Experienced animal welfare officer
Project controller to the nature and water department, substitute
Seasonal work - park work, substitute
Holiday work at Lantmännen Unibake, Örebro
Unit manager, protection and development, nature and water department
Postdoctoral - Multifunctionality in diversified agroecosystems
Research Assistant
Production adviser in southeastern and southwestern Sweden
Agronomist - Horticulture Officer
Versatile- animal agricultural worker M/F
Carutier h / f
Agrifood production agent M/F
Recipe preparer in food industry M/F
Plant engineering consultant
Supervisor Garden facility
PhD student position in land sector sustainability transitions
We are looking for quality lines for our factory in Kungshamn!
Production Manager
Agronomist to Statistics Sweden
GreenThe coach for assignments in Lund
Greenish coaches for assignments in Lomma
GreenThe coach to assignment in Staffanstorp
Site Construction Manager
Data Scientist in remote sensing (f/h)
Postdoctoral inom Best Mans Analysis of Fish
Postdoctoral fellow in stock assessment
Action Coordinator in Water to Heby Municipality
Investigators in sea plans
Farm workers farmer, plant cultivation, soil, forest, animals
Chief the project sap - OTC (F / H)
Data Analyst Smart Pricing (F/H)
Proximity computer support technician - Le Mans (72) - F/H
Data H/F strategy project manager
F/H System Engineer
Executive Legal & Strategic Assistant
Digital project manager - Finance (F/H)
CDI Data Scientist Modelisation 2 postes (F/H/NB)
Junior Product Manager
Technico-commercial H/F
Caviste H/F
Automated Installations Driver M/F
ING MAINTENANCE TECHNICIAN PORT EQUIPMENT SPECIALIST
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Endowed Professor (Tenured) in Maritime Management
Director/Deputy Director, Animal Research Facility [LKCMedicine]
LABORATORY ANIMAL
TECHNICIAN-MARKETING
WESTERN GREECE SALES DEPARTMENT
IT Service Manager M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
IT Service Manager M/F
Day Maintenance Technician M/F
Quality Facilitator M/F
Installation Technicians
Installation Technicians
Installation Technicians
Quality Facilitator M/F
Technico-commercial H/F
Landscape team leader M/F
Experienced wine worker (M/F)
Poultry worker M/F
After-sales service technician M/F
Landscape team leader M/F
Automated Installations Driver M/F
Caviste H/F
Agriculturalist
Production Manager / Site Manager (m/f/d)
Deputy housekeeping manager m/f/d
Agricultural mechanic M/F
Landscape team leader M/F
Skipper for Svensk Sjöentreprenad in Malmö
Foreman, Agricultural machinery
Environmental officer for the Air Staff
Senior environmental advisor - marine environment
Project manager at the Rural Development Unit
Sales warehouse manager in agricultural products
Electrical Engineer
Staff scientist in biophysics
Researcher
Research assistant
Are you our new water manager?
Are you our new water manager?
Property manager
Payroll specialist
Structural Analysis Engineer
Validation engineer for Saab in Linköping!

1681 returned jobs

## Filter jobs

Many of the job offers, although they contain the keywords and the occupations we searched for, they are not relevant to agriculture.

We are going to filter them based on the occupations labels that we stored above.

## filtering according to skills

We already have a set of skills related (optionally or significantly) to agriculture extracted by ESCO database.
We are going to exclude any job offer that has no skills that belong to that set

In [ ]:
import pandas as pd

try:
  df = pd.read_csv("/content/EssentialAgriculturalSkills.csv")

  relevant_esco_skills = df.set_index('skill').to_dict(orient='index')
except FileNotFoundError:
  print("File not found.")

def filter_according_to_skills(jobs_data, relevant_skills):
    accepted = {}
    rejected = {}
    for job in jobs_data.get('items'):
      for skill_id in job.get('skills'):
        if skill_id in relevant_skills:
          accepted[job['id']] = job
          break
      if job['id'] not in accepted.keys():
        rejected[job['id']] = job

    return accepted, rejected

accepted, rejected = filter_according_to_skills(jobs_data, relevant_esco_skills)
print_filter_results(accepted, rejected)

Total number of accepted jobs: 971
Total number of rejected jobs: 710
--- Accepted Jobs ---
MANAGER OF PRODUCTION - 1659
Agricultural Sales - Export Managers - 2638
Farm Veterinarian - 2893
Veterinary - 3237
Senior Consultant Agriculture and Food Sector F/M - 6744
Agro Logistics Manager M/F - 20230
Agro Logistics Manager - 22502
Agricultural workshop manager - 26782
Agricultural mechanic M/F - 26783
Versatile agricultural worker M/F - 28966
Poultry worker M/F - 29242
Poultry worker M/F - 29282
Landscape gardener M/F - 30088
Agricultural Technician M/F - 30540
Land and Agricultural Estate Operations Director M/F - 31908
Day Maintenance Technician M/F - 32661
Maintenance and New Works Technician M/F - 32677
Technician, Animal Research Facility [LKCMedicine] - 37758
Technician, Animal Research Facility [LKCMedicine] - 37759
LABORATORY ANIMAL - 40398
LABORATORY ANIMAL - 40542
Agronomic R&D Technician | Agronomist - 45646
Agronomic R&D Technician | Agronomist - 45647
Agronomic R&D Technician | Agronomist - 45653
digital domain manager F/M - 52208
Director of Poultry Operations M/F - 61359
Agronomic R&D Technician | Agronomist - 61744
Food Quality and Safety System Manager M/F - 63000
Day Maintenance Technician M/F - 63540
Head of the Digital Product Development Department M/F - 65112
Subsidiary Manager M/F - 65151
Subsidiary Manager M/F - 65153
Versatile agricultural worker M/F - 71654
Industrial maintenance technician M/F Domaine Avicole - 72038
Chauffeur SPL* H/F - 73928
Poultry worker M/F - 74028
Agricultural mechanic M/F - 77751
Land and Agricultural Estate Operations Director M/F - 79161
Sole Accountant M/F - 79265
Day Maintenance Technician M/F - 80351
Head of culture M/F - 82355
Day Maintenance Technician M/F - 91684
Station Manager - 92925
Veterinarian | Scientific Officer - 100780
Plant Innovation Manager F/M - 101775
Versatile agricultural worker - Animal worker M/F - 104496
Workshop Manager 3*8 M/F - 107600
Day Maintenance Technician M/F - 109562
Poultry worker M/F - 111027
Chauffeur SPL* H/F - 111073
Head of the Digital Product Development Department M/F - 113565
Subsidiary Manager M/F - 113583
Subsidiary Manager M/F - 113585
Food Quality and Safety System Manager M/F - 113991
Day Maintenance Technician M/F - 114191
Advisor with a focus on robust primary production within Greppa Näringen - 116584
Doctoral student in beef production on natural pastures - 117711
Sales manager north, Väktodling - 123970
Researchers - bioinformatics and adaptation of crops to climate change - 126884
Expert/project manager in milk for sustainable animal production - 134508
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 141059
Researchers with a focus on advanced analysis of fish behavior - 141182
Bath water technician for new assignment in Täby - 143225
Veterinarian with an interest in infectious diseases in poultry - 143710
Veterinarian with an interest in infectious diseases in poultry - 143824
Contingency manager with a focus on project management - 145340
Administrators and advisors with a focus on farm animals - 145804
Contingency manager with a focus on the development of forms of support - 145866
Contingency manager with a focus on project management - 146204
Post-doc position on the quality of the dead wood and dead-wood dependent organisms - 148475
Postdoc position in deadwood quality and saproxylic communities - 148479
Teacher in agricultural subjects - Komvux - 150232
Agricultural adviser to the Councilors in Sjuhärad - 151290
Business manager for the new center for sustainable primary production - 153865
Farm worker/excavator - 156338
Summer job 2025;     Tractor driver for Widegrens Gård on Gotland - 156728
Tractor and machine operator for Widegrens Gård on Gotland - 156744
Professor in Business Studies - 156828
Postdoc in agricultural water management - 160337
Doctoral position in modeling of plant-environment and plant-plant interactions - 162786
PhD in modelling plant-environment and plant-plant interactions - 162787
Committed and relationship-building production manager for Sydvatten - 171793
Water Equipment Maintenance Technician M/F - 176375
Responsable des Opérations H/F - 176708
Animal care employee or animal care assistant (f/m/d) - 178509
University lecturer in plant ecology - 181377
Senior Lecturer/Associate Professor* in Plant Ecology - 181409
Development leader within Community Building - 182036
Doctoral student, Biology - plant pathology and resistance breeding - 183256
PhD student, Biology - Plant Pathology and Resistance Breeding - 183428
Acting supervisor in animal welfare - 183619
Syngenta Group China Scientist - 184552
Animal welfare officer - 184576
Animal welfare officer - 184748
Researcher in Bioinformatics and crop adaptation to climate change - 185905
Contingency manager with a focus on the development of forms of support - 187253
MARKETING MANAGER FOR KONVEX AB - 189896
Senior Consultant Agriculture and Food Sector F/M - 1526963
digital domain manager F/M - 1565152
Plant Innovation Manager F/M - 1609775
Advisor with a focus on robust primary production within Greppa Näringen - 1623928
Doctoral student in beef production on natural pastures - 1625055
Sales manager north, Väktodling - 1631314
Researchers - bioinformatics and adaptation of crops to climate change - 1634228
Expert/project manager in milk for sustainable animal production - 1641777
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 1647466
Researchers with a focus on advanced analysis of fish behavior - 1647589
Bath water technician for new assignment in Täby - 1649632
Veterinarian with an interest in infectious diseases in poultry - 1650117
Veterinarian with an interest in infectious diseases in poultry - 1650231
Contingency manager with a focus on project management - 1651747
Administrators and advisors with a focus on farm animals - 1652211
Contingency manager with a focus on the development of forms of support - 1652273
Contingency manager with a focus on project management - 1652611
Post-doc position on the quality of the dead wood and dead-wood dependent organisms - 1654882
Postdoc position in deadwood quality and saproxylic communities - 1654886
Teacher in agricultural subjects - Komvux - 1656639
Agricultural adviser to the Councilors in Sjuhärad - 1657697
Business manager for the new center for sustainable primary production - 1660272
Farm worker/excavator - 1662745
Summer Job 2025;     Tractor Driver For Widegrens Gård On Gotland - 1663135
Tractor and Machine Operator for Widegrens Gård on Gotland - 1663151
Professor in Business Studies - 1663235
Postdoc in agricultural water management - 1666744
Doctoral position in modeling of plant-environment and plant-plant interactions - 1669193
PhD in modelling plant-environment and plant-plant interactions - 1669194
University lecturer in plant ecology - 1685984
Senior Lecturer/Associate Professor* in Plant Ecology - 1686016
Development leader within Community Building - 1686643
Doctoral student, Biology - plant pathology and resistance breeding - 1687863
PhD student, Biology - Plant Pathology and Resistance Breeding - 1688035
Acting supervisor in animal welfare - 1688226
Syngenta Group China Scientist - 1689159
Animal welfare officer - 1689183
Animal welfare officer - 1689355
Researcher in Bioinformatics and crop adaptation to climate change - 1690512
Contingency manager with a focus on the development of forms of support - 1691860
MARKETING MANAGER FOR KONVEX AB - 1694503
PLANT PRODUCTION FARMER (XANTHI) - 1695147
Training to become a cattle farming specialist (m/f/d) - 1697286
Technical assistant (m/f/d) breeding garden - 1698582
Technical Support Engineer - 1700970
Application expert - 1702378
Operations manager SLU Lanna Property - 1702404
Naturbrukskolan Uddetorp is looking for a special teacher in mathematics - 1702439
Substitute Cultivation coordinator/project manager - 1702872
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 1703236
Researchers, Effect of temperature-induced germ line determination in plants - 1705275
Work with plant protection - three services in our socially important business - 1705490
Animal welfare officer - 1706672
Agricultural adviser to the Councilors in Sjuhärad - 1706977
Naturbrukskolan Uddetorp is looking for a cook - 1707320
Plant cultivation advisor to the Housekeeping Society Kalmar Kronoberg Blekinge - 1708081
Coordinating Production Manager - 1709877
Scientist in plant molecular biology and genetics - 1714512
Natural School Uddetorp is looking for two student coaches - 1715420
Plant cultivation adviser to the Housekeeping Society Kalmar Kronoberg Blekinge - 1717705
Biträdande rektor till Munkagårdsgymnasiet - 1721447
Badvattentekniker till nytt uppdrag i Täby - 1724357
Kundansvarig till Biototal Group i Skåne - 1725773
Γεωπόνους Πωλήσεων - Export Managers - 1726200
Forskare - 1735433
DSS eller veterinär med chefsuppdrag för operationsenheten - 1736095
Kundansvarig till Biototal med arbetsområde Gävle med omnejd - 1736520
Forskare, laboratoriestudier på torvjord - 1739806
Responsable de pôle installation en agriculture (F/H) - 1743589
Herdenmanager m/w/d - 1745044
Gärtner*in (m/w/d) mit Fachrichtung Gemüsebau - 1746457
Djurskyddshandläggare med fokus på lantbrukets djur - 1749919
Stalltekniker - 1752303
Postdoc - Plant breeding towards nutritional quality in cereals - 1752439
Postdoktor i biologi med fokus på fiskekologi och hydrologi - 1752866
Butiks- och reservdelssäljare - 1753456
Vi söker lantbruksekonomer och redovisningskonsulter - 1756129
Chef till Landsbygdsavdelningen, Funktionen för Djurskydd - 1756589
Researcher Rural Development - 1758448
Parkingenjör till Parkenheten - 1759287
Djurvårdare/DSS/Veterinär med chefsuppdrag för vård-och operationsenheten - 1759482
Butiks- och reservdelssäljare - 1761795
Butiks- och reservdelssäljare - 1762076
Växtodlingssäljare - 1762483
Magasinier H/F - 1769732
Postdoktor i akvatisk ekologi - 1771536
Tekniker - 1772439
Doktorand inom växtbiologi med fokus på cellväggens dynamik - 1773158
Stadsbonde för kunskapshöjande odling inom staden - 1774835
Produktadministratör - 1775627
Djurskyddshandläggare - 1778218
Badvattentekniker till nytt uppdrag i Täby - 1782683
Agraringenieur/ Anbauberater (m/w/d) - 1785933
Försökstekniker - 1787132
Produktionsledare/Driftledare med inriktning dikor och växtodling Svartsjö - 1788922
Universitetslektor i skogspatologi - 1792872
Senior Lecturer (Associate Professor) in Forest Pathology - 1793762
Vi söker lantbruksekonomer och redovisningskonsulter - 1793813
Badvattentekniker till nytt uppdrag i Täby - 1794055
Βοηθός Παραγωγής Καλλωπιστικών Φυτών - 1800323
Agronomic R&D Researcher | Γεωπόνος - 1800329
Agronomic R&D Researcher | Γεωπόνος - 1800331
Secodi Technicien itinérant H/F - 1802585
BMA med uppdrag som enhetschef för Klinisk kemiska laboratoriet, SLU - 1811078
Assistent till Kriscentrums skyddade boenden - 1811408
Forskningsassistent - 1812161
Berga söker en driftig växtodlings lärare - 1812470
Kvalitetsansvarig Jord - Forma framtidens hållbara jordproduktion med oss! - 1813024
Naturbrukslärare Växtodling - 1813247
Rådgivare inom växtodling till kunskapsnav miljö och klimat - 1813350
Postdoktor: Växthusgasutsläpp från jordar och metoder för att minska dem - 1813373
Post doc  Mapping aquatic resources in a changing climate - 1815155
Trädgårdsmästare - 1818851
Amanuens - 1819873
Fastighetsskötare vid Institutionen för akvatiska resurser - 1820158
Technical Sales Representative - 1820244
Pedagog till S:t Hansgården - 1820624
Vi söker växtodlingsrådgivare till växtskyddscentralen i Landskrona - 1824076
Handläggare för restaurering av vatten- och våtmarksmiljöer - 1824295
ΓΕΩΠΟΝΟΣ ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ (ΞΑΝΘΗ) - 1826439
Agronomic R&D Specialist| Γεωπόνος - Λάρισα - 1826527
Agronomic R&D Specialist | Γεωπόνος - 1826529
Kundansvarig Uppsala - 1831136
Kundansvarig till Biototal Group i Skåne - 1831622
Laboratoriechef vid institutionen för mark och miljö - 1832702
Agronomist - 1836155
Driftschef - 1837786
Regional åtgärdssamordnare för fysiska åtgärder - 1839273
Växtodlingsrådgivare Dalarna - 1840380
Professor of Bioinformatics - 1840525
ΓΕΩΠΟΝΟΣ ΣΤΕΛΕΧΟΣ ΠΩΛΗΣΕΩΝ B2B - 1843233
CTO / Tech lead (H/F) REF 8209-JE - 1845839
Butiks- och reservdelssäljare - 1848484
Traktorförare Säsong 2025 - 1852203
Badvattentekniker till nytt uppdrag i Täby - 1853498
Regionchef - 1854335
Driftledare Växtodling - 1856862
Naturbruksskolan Sötåsen söker vikarierande lärare i svenska och engelska - 1857383
PhD in Aquatic Ecology: Hydropower impacts on lake function & biodiversity - 1858446
Εργασία σε Παραγωγή Καλλωπιστικών Φυτών - 1860660
Business Analyst - 1860792
MDM Developer | HT2025PM0106 - 1862844
Mécanicien agricole H/F - 1865627
Maraîcher H/F - 1867000
Sales intern (praktikant) - 1869435
Agronom/ biolog med fokus på kvalitetsstyrning (kvalitetskoordinator) - 1869555
Medarbetare till enheten för jordbruk och livsmedelsföretagande - 1872827
Medarbetare till enheten för jordbruk och livsmedelsföretagande - 1872889
Postdoctoral researcher in dairy cattle grazing - 1873211
Senior Lecturer in Chemical Ecology with a focus on Disease Vectors - 1876221
Postdoktor - tillväxt och försvar hos Brassica napus - 1877470
Trädgård och markskötsel på AstraZeneca i Mölndal - 1878009
Varmköks ansvarig till butiksköket - 1880124
Utredare, inriktning  ekonomisk modellering och miljöeffekter av pesticider - 1880590
Traktorförare Säsong 2025 - 1880592
Professor i One Health med inriktning livsmedelsproduktion - 1882573
Naturbruksskolan Sötåsen söker vikarierande lärare i svenska och historia - 1884532
ERP Data Analyst & Reporting Specialist - 1885480
ENSEIGNANT-CHERCHEUR EN GEO DATA SCIENCE (F/H) - 1886881
Enhetschef, skydd och utveckling, Natur- och vattenavdelningen - 1888041
Postdoc - data-driven approaches for improved crop protection - 1888937
Enhetschef, skydd och utveckling, Natur- och vattenavdelningen - 1890891
Djurskyddshandläggare - 1891353
Postdoktor - data-drivna metoder för förbättrat växtskydd - 1891627
One postdoc - multifunctionality of diversified agroecosystems - 1891674
Säsongsarbetare till Vattenenheten - 1899018
Vi söker två agronomer eller lantmästare med jordbruksföretaget i fokus - 1899684
Forskande veterinär med hästkompetens sökes! - 1903378
Professor of One Health with focus on food production - 1905662
Naturbruksskolan Sötåsen söker lärare matematik/speciallärare - 1906075
Agronomic R&D Specialist| Γεωπόνος - Κρήτη - 1906893
Horticultural Specialist till Swegreen - 1914224
Rector of Forslundagymnasiet - 1914710
Natural technician for the nature conservation unit - 1914847
Production controller - 1915197
Head of Department Nature and Water Department - 1915936
Manager to the dog section Swedec - 1916512
Lageransvarig Victorsson Poultry AB - 1918265
PhD Student in Plant Genetics and Breeding - 1924199
Animal Technician to AZ in Gothenburg - 1925361
Nursery school to Billbäcks Nursery - 1926738
PhD Position in Disease and Restoration Ecology - 1928762
Marketing managers to department in agriculture, food and cycle technology - 1929140
Doctoral student in disease and restoration ecology - 1930005
Natural School Sweet Seeks Teacher Mathematics - 1930112
Animal caretakers with cousin competence - 1934889
Experienced animal welfare officer - 1935340
Project controller to the nature and water department, substitute - 1935831
Seasonal work - park work, substitute - 1936024
Unit manager, protection and development, nature and water department - 1937704
Postdoctoral - Multifunctionality in diversified agroecosystems - 1938159
Research Assistant - 1938940
Production adviser in southeastern and southwestern Sweden - 1939414
Agronomist - Horticulture Officer - 1940197
Versatile- animal agricultural worker M/F - 1942032
Recipe preparer in food industry M/F - 1945766
Plant engineering consultant - 1947969
Supervisor Garden facility - 1949530
PhD student position in land sector sustainability transitions - 1955393
Production Manager - 1957581
Site Construction Manager - 2080946
Data Scientist in remote sensing (f/h) - 2084207
Postdoctoral fellow in stock assessment - 2768666
Action Coordinator in Water to Heby Municipality - 2770740
Farm workers farmer, plant cultivation, soil, forest, animals - 2772113
Data Analyst Smart Pricing (F/H) - 2786103
Data H/F strategy project manager - 2786662
Junior Product Manager - 2803
Caviste H/F - 22777
Automated Installations Driver M/F - 31431
Director/Deputy Director, Animal Research Facility [LKCMedicine] - 37558
IT Service Manager M/F - 57818
IT Service Manager M/F - 59176
Day Maintenance Technician M/F - 61220
Quality Facilitator M/F - 63570
Quality Facilitator M/F - 67959
Experienced wine worker (M/F) - 72877
Poultry worker M/F - 73969
Automated Installations Driver M/F - 78711
Caviste H/F - 83448
Production Manager / Site Manager (m/f/d) - 88086
Agricultural mechanic M/F - 98156
Foreman, Agricultural machinery - 117800
Environmental officer for the Air Staff - 121314
Senior environmental advisor - marine environment - 122667
Staff scientist in biophysics - 130559
Researcher - 140000
Property manager - 148201
Payroll specialist - 150047
Structural Analysis Engineer - 150719
Validation engineer for Saab in Linköping! - 150767
Technical Product Manager - 150805
Postdoc in microbial ecology - 151058
University lecturer in economics - 156821
Researchers Marine extreme weather and climate risks for fisheries - 156858
Professor of Business Administration - 156938
Researcher  Marine extreme weather and climate risks for fisheries - 157029
Senior lecturer/Associate professor* in agricultural and food economics - 157180
Stable technician - 159328
Doctoral student in fodder production, feeding and pasture management - 183243
Operations manager for new fish research laboratory - 186336
Support technician for Sweden's geological survey - 187385
Support technician for Sweden's geological survey - 187499
IT Service Manager M/F - 1567924
Foreman, Agricultural machinery - 1625144
Environmental officer for the Air Staff - 1628658
Senior environmental advisor - marine environment - 1630011
Staff scientist in biophysics - 1637828
Researcher - 1646407
Property manager - 1654608
Payroll specialist - 1656454
Structural Analysis Engineer - 1657126
Validation engineer for Saab in Linköping! - 1657174
Technical Product Manager - 1657212
Postdoc in microbial ecology - 1657465
University lecturer in economics - 1663228
Researchers Marine extreme weather and climate risks for fisheries - 1663265
Professor of Business Administration - 1663345
Researcher  Marine extreme weather and climate risks for fisheries - 1663436
Senior lecturer/Associate professor* in agricultural and food economics - 1663587
Stable technician - 1665735
Doctoral student in fodder production, feeding and pasture management - 1687850
Operations manager for new fish research laboratory - 1690943
Support technician for Sweden's geological survey - 1691992
Support technician for Sweden's geological survey - 1692106
Training as a cattle carer (m/f/d) specializing in cattle husbandry - 1697284
Training to become a cattle carer (m/f/d) - 1697285
Training as an animal farmer (m/f/d) specializing in cattle farming - 1697296
AGRARBETRIEBSWIRTIN/AGRARBETRIEBSWIRT (M/W/D) - 1698913
Zookeeper milk - 1702319
Language teacher in English and Swedish - 1708363
Pig keeper - 1709656
Vocational teachers in machine and natural use - 1713772
Research Assistant at Grimsö Research Station - 1716230
Property manager - 1719255
Biträdande rektor till Naturbruksskolan Sötåsen - 1723841
Administrativ handläggare till enheten för djurskydd - 1724501
Senior-Softwarearchitekt/in für innovative Agrartechnologien (m/w/d) - 1728874
Funktionschef - djurskyddsfunktionen - 1732403
Researcher in Tropical Lepidoptera - 1732451
Forskare, tropiska Lepidoptera - 1732589
Gårdsansvarig - 1739844
Underhållsmekaniker - 1750590

In [ ]:
a,b,c = analyze_job_result(rejected ,justified_keywords, occupations_data, job_title="Cattle keeper, in agriculture")

--- Selected Job ---
{'description': 'Prästbol is a modern agricultural company in Södra Värmland. '
                'Here, beef production and plant cultivation are carried out '
                'on roughly 500 ha of land. In addition, there are some '
                'natural pastures and 100 ha of forest. We are looking for an '
                'employee for agriculture, where various work is included. You '
                'need to have at least 3 years of experience working with '
                'cattle and have an interest in animal handling. You also need '
                'to have an interest in crop cultivation and be able to drive '
                'a tractor and loader. We are looking for someone who is '
                'organized and easy to work with. It is good if you know '
                'Swedish and English. The work involves varied tasks. It is '
                'important that you are the right person. A first contact '
                'should be made via email to the employer at: '
                'johanssonjanch@gmail.com',
 'experience_level': 'nan',
 'id': 151200,
 'location': 'Karlstad, Sweden',
 'location_code': 'SE',
 'nuts1': None,
 'nuts2': None,
 'nuts3': None,
 'occupations': ['http://data.europa.eu/esco/occupation/7e33b166-4a6d-40f3-8048-83b3a9d3ef49',
                 'http://data.europa.eu/esco/occupation/b4ff30f8-073b-4dd8-9128-ecf9d0ff87ba',
                 'http://data.europa.eu/esco/occupation/c9191f7f-28b5-4df8-991d-804c53009b83',
                 'http://data.europa.eu/esco/isco/C611'],
 'organization': None,
 'skills': [],
 'source': 'jobbland',
 'source_id': '18637543',
 'title': 'Cattle keeper, in agriculture',
 'type': 'nan',
 'upload_date': '2024-10-06'}


--- Similar Keywords ---
[]


--- Similar Occupations Based on Fuzzy Match ---


--- Similar Occupations ---
cattle breeder
crop production worker
Market gardeners and crop growers

In [ ]:
def filter_according_to_occupations(jobs_data, occupations_data):
  accepted = {}
  rejected = {}
  occupation_ids = list({occupation.get('id') for occupation in occupations_data.get('items')})
  for job in jobs_data.values():
    relevant_occupations = []
    for occupation_id in occupation_ids:
      if occupation_id in job.get('occupations'):
        relevant_occupations.append(occupation_id)
    if len(relevant_occupations)/len(job.get('occupations')) >= 0.3:
      accepted[job['id']] = job
    else:
      rejected[job['id']] = job

  return accepted, rejected

Total number of accepted jobs: 268
Total number of rejected jobs: 703
--- Accepted Jobs ---
MANAGER OF PRODUCTION - 1659
Farm Veterinarian - 2893
Veterinary - 3237
Senior Consultant Agriculture and Food Sector F/M - 6744
Versatile agricultural worker M/F - 28966
Poultry worker M/F - 29242
Poultry worker M/F - 29282
Agricultural Technician M/F - 30540
Land and Agricultural Estate Operations Director M/F - 31908
Day Maintenance Technician M/F - 32661
Agronomic R&D Technician | Agronomist - 45646
Agronomic R&D Technician | Agronomist - 45647
Agronomic R&D Technician | Agronomist - 45653
digital domain manager F/M - 52208
Agronomic R&D Technician | Agronomist - 61744
Day Maintenance Technician M/F - 63540
Versatile agricultural worker M/F - 71654
Industrial maintenance technician M/F Domaine Avicole - 72038
Chauffeur SPL* H/F - 73928
Poultry worker M/F - 74028
Agricultural mechanic M/F - 77751
Land and Agricultural Estate Operations Director M/F - 79161
Day Maintenance Technician M/F - 80351
Head of culture M/F - 82355
Day Maintenance Technician M/F - 91684
Station Manager - 92925
Veterinarian | Scientific Officer - 100780
Plant Innovation Manager F/M - 101775
Versatile agricultural worker - Animal worker M/F - 104496
Day Maintenance Technician M/F - 109562
Poultry worker M/F - 111027
Chauffeur SPL* H/F - 111073
Day Maintenance Technician M/F - 114191
Sales manager north, Väktodling - 123970
Expert/project manager in milk for sustainable animal production - 134508
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 141059
Administrators and advisors with a focus on farm animals - 145804
Agricultural adviser to the Councilors in Sjuhärad - 151290
Business manager for the new center for sustainable primary production - 153865
Farm worker/excavator - 156338
Summer job 2025;     Tractor driver for Widegrens Gård on Gotland - 156728
Tractor and machine operator for Widegrens Gård on Gotland - 156744
Animal care employee or animal care assistant (f/m/d) - 178509
Syngenta Group China Scientist - 184552
Animal welfare officer - 184576
Senior Consultant Agriculture and Food Sector F/M - 1526963
digital domain manager F/M - 1565152
Plant Innovation Manager F/M - 1609775
Sales manager north, Väktodling - 1631314
Expert/project manager in milk for sustainable animal production - 1641777
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 1647466
Administrators and advisors with a focus on farm animals - 1652211
Agricultural adviser to the Councilors in Sjuhärad - 1657697
Business manager for the new center for sustainable primary production - 1660272
Farm worker/excavator - 1662745
Summer Job 2025;     Tractor Driver For Widegrens Gård On Gotland - 1663135
Tractor and Machine Operator for Widegrens Gård on Gotland - 1663151
Syngenta Group China Scientist - 1689159
Animal welfare officer - 1689183
PLANT PRODUCTION FARMER (XANTHI) - 1695147
Training to become a cattle farming specialist (m/f/d) - 1697286
Technical assistant (m/f/d) breeding garden - 1698582
Application expert - 1702378
Operations manager SLU Lanna Property - 1702404
Substitute Cultivation coordinator/project manager - 1702872
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 1703236
Work with plant protection - three services in our socially important business - 1705490
Agricultural adviser to the Councilors in Sjuhärad - 1706977
Plant cultivation advisor to the Housekeeping Society Kalmar Kronoberg Blekinge - 1708081
Plant cultivation adviser to the Housekeeping Society Kalmar Kronoberg Blekinge - 1717705
Kundansvarig till Biototal Group i Skåne - 1725773
Kundansvarig till Biototal med arbetsområde Gävle med omnejd - 1736520
Responsable de pôle installation en agriculture (F/H) - 1743589
Herdenmanager m/w/d - 1745044
Gärtner*in (m/w/d) mit Fachrichtung Gemüsebau - 1746457
Djurskyddshandläggare med fokus på lantbrukets djur - 1749919
Stalltekniker - 1752303
Postdoc - Plant breeding towards nutritional quality in cereals - 1752439
Vi söker lantbruksekonomer och redovisningskonsulter - 1756129
Magasinier H/F - 1769732
Postdoktor i akvatisk ekologi - 1771536
Stadsbonde för kunskapshöjande odling inom staden - 1774835
Agraringenieur/ Anbauberater (m/w/d) - 1785933
Försökstekniker - 1787132
Produktionsledare/Driftledare med inriktning dikor och växtodling Svartsjö - 1788922
Vi söker lantbruksekonomer och redovisningskonsulter - 1793813
Βοηθός Παραγωγής Καλλωπιστικών Φυτών - 1800323
Agronomic R&D Researcher | Γεωπόνος - 1800329
Agronomic R&D Researcher | Γεωπόνος - 1800331
Trädgårdsmästare - 1818851
Technical Sales Representative - 1820244
Vi söker växtodlingsrådgivare till växtskyddscentralen i Landskrona - 1824076
ΓΕΩΠΟΝΟΣ ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ (ΞΑΝΘΗ) - 1826439
Agronomic R&D Specialist| Γεωπόνος - Λάρισα - 1826527
Agronomic R&D Specialist | Γεωπόνος - 1826529
Kundansvarig Uppsala - 1831136
Kundansvarig till Biototal Group i Skåne - 1831622
Agronomist - 1836155
Växtodlingsrådgivare Dalarna - 1840380
ΓΕΩΠΟΝΟΣ ΣΤΕΛΕΧΟΣ ΠΩΛΗΣΕΩΝ B2B - 1843233
Traktorförare Säsong 2025 - 1852203
Regionchef - 1854335
Driftledare Växtodling - 1856862
Εργασία σε Παραγωγή Καλλωπιστικών Φυτών - 1860660
Mécanicien agricole H/F - 1865627
Maraîcher H/F - 1867000
Sales intern (praktikant) - 1869435
Trädgård och markskötsel på AstraZeneca i Mölndal - 1878009
Utredare, inriktning  ekonomisk modellering och miljöeffekter av pesticider - 1880590
Traktorförare Säsong 2025 - 1880592
Säsongsarbetare till Vattenenheten - 1899018
Vi söker två agronomer eller lantmästare med jordbruksföretaget i fokus - 1899684
Agronomic R&D Specialist| Γεωπόνος - Κρήτη - 1906893
Horticultural Specialist till Swegreen - 1914224
Head of Department Nature and Water Department - 1915936
PhD Student in Plant Genetics and Breeding - 1924199
Nursery school to Billbäcks Nursery - 1926738
Research Assistant - 1938940
Agronomist - Horticulture Officer - 1940197
Versatile- animal agricultural worker M/F - 1942032
Plant engineering consultant - 1947969
PhD student position in land sector sustainability transitions - 1955393
Postdoctoral fellow in stock assessment - 2768666
Farm workers farmer, plant cultivation, soil, forest, animals - 2772113
Data H/F strategy project manager - 2786662
Caviste H/F - 22777
Automated Installations Driver M/F - 31431
IT Service Manager M/F - 57818
IT Service Manager M/F - 59176
Day Maintenance Technician M/F - 61220
Quality Facilitator M/F - 63570
Quality Facilitator M/F - 67959
Experienced wine worker (M/F) - 72877
Poultry worker M/F - 73969
Automated Installations Driver M/F - 78711
Caviste H/F - 83448
Foreman, Agricultural machinery - 117800
Property manager - 148201
Stable technician - 159328
IT Service Manager M/F - 1567924
Foreman, Agricultural machinery - 1625144
Property manager - 1654608
Stable technician - 1665735
Training as a cattle carer (m/f/d) specializing in cattle husbandry - 1697284
Training to become a cattle carer (m/f/d) - 1697285
Training as an animal farmer (m/f/d) specializing in cattle farming - 1697296
AGRARBETRIEBSWIRTIN/AGRARBETRIEBSWIRT (M/W/D) - 1698913
Zookeeper milk - 1702319
Pig keeper - 1709656
Vocational teachers in machine and natural use - 1713772
Gårdsansvarig - 1739844
Phd position within Sustainable Feed for Poultry and Pigs - 1751148
Postdoktor - Växtförädling för förbättrad näringskvalitet i spannmål - 1751994
Är du vår nästa maskinförare? Arbeta med modern utrustning i Vinslöv! - 1772492
Östergårds Grönsaker söker maskinförare! - 1774418
Försökstekniker till Sandbygård - 1776420
Senior Farm Sustainability Specialist - Viby, Stockholm or Düsseldorf. Remote working is possible. - 1780515
Är du vår nästa maskinförare? Arbeta med modern utrustning i Vinslöv! - 1788723
Växthusarbetare till food tech-bolag - 1791866
Växthusarbetare till food tech-bolag - 1792086
Maskinförare till ledande lantbruk i Vinslöv! - 1794245
Växthusarbetare till food tech-bolag (deltid) - 1809849
Växthusarbetare till food tech-bolag (deltid) - 1813715
Är du vår nästa maskinförare? Arbeta med modern utrustning i Vinslöv! - 1817157
Redovisningskonsult med avdelningsansvar - 1819381
Field staff wanted for field-based forest research during season 2025 - 1819635
Jobb för maskinförare - sök nu! - 1819918
Försökstekniker till Borgeby/Helgegården - 1823589
Försökstekniker till Borgeby/Helgegården - 1823755
Jobb för maskinförare - sök nu! - 1824383
Östergårds Grönsaker söker maskinförare! - 1824791
Jobb för maskinförare - sök nu! - 1835897
Försöksassistent - 1841619
Maskinförare växtodling - 1853395
Medarbetare till Christinelunds Gård - 1854356
Lantbrukare med huvudansvar för jordbruk och djurhållning - 1854878
Chef till funktionen Jordbrukarstöd - 1870403
Maskinförare,Lantarbetare Öjeby Gård - 1879631
DATA ANALYST F/H - 1887173
Avbytare Växa Sverige Laholm - 1889800
Betriebsleiter (m/w/d) im Obstbau - 1912288
Employees plant cultivation attempts - 1923021
Researchers in ecosystem services in strip cultivation - 1923458
Seasonal employee for organic vegetable cultivation on southern Gotland - 1932996
Market gardener H/F - 1943093
Summer job: substitute as a city farmer! - 2777019
Doctorant F/H Measuring brain microstructure through myelin content modelling in neurodegenerative diseases - 8578
SILO Storekeeper M/F - 25850
Landscape mason M/F - Temporary - Cluses - 28848
Landscape mason M/F - Temporary - Magland - 28943
Landscape mason M/F - CDI Sallanches - 28944
Landscape mason M/F - Temporary - Sallanches - 28990
Landscape mason M/F - CDI Magland - 28991
Växa is looking for an Expert in sustainability - 123574
Accounting consultant to Rådgivarna in Sjuhärad - 156301
Driftmaskinist - 185137
Doctorant F/H Measuring brain microstructure through myelin content modelling in neurodegenerative diseases - 1528797
Växa is looking for an Expert in sustainability - 1630918
Accounting Consultant to the advisers in Sjuhärad - 1662708
Driftmaskinist - 1689744
Pig production foreman - 1709715
Lantbruksarbete med fokus på växtodling och maskiner - 1737387
Lantbruksarbetare för ekologisk odling av indiska grönsaker - 1751210
Agronom, Forslundagymnasiet - 1807209
Vi söker nu en engagerad och ansvarstagande Gårdsansvarig till våra gårdar! - 1807732
Gårdsansvarig - 1812660
Jordbruksverket söker säsongsanställda till växtskyddscentralerna! - 1819507
Växa Sverige söker Kokontrollexpert! - 1824439
Distriktssäljare till DeLaval - 1830961
Distriktssäljare till DeLaval - 1830962
Gårdsansvarig - 1830982
Distriktssäljare till DeLaval - 1830984
Distriktssäljare till DeLaval - 1831743
Distriktssäljare till DeLaval - 1856825
Distriktssäljare till DeLaval - 1857125
Distriktssäljare till DeLaval - 1857231
Distriktssäljare till DeLaval - 1857232
Distriktssäljare i Skåne - 1857405
Farmer as a stable manager "Herdsman/Herdswoman" m/f/d - 1863420
Driftledare Lantbruk Öjeby Gård - 1879498
Samordnare för stadsnära odling - 1895320
Gårdsansvarig - 1899103
Trädgårdsmedarbetare kort säsong - 1902760
Support Manager with knowledge of agriculture - Strengthen precision agriculture and field planning with Näsgård - 1913493
Plant protection officer nursery school to Billbäcks Nursery - 1927093
Machine driver plant cultivation - 1938990
Farmer as a stable manager "Herdsman/Herdswoman" m/f/d - 1947973
contract researcher F/H LCA of agricultural systems producing biogas by methanization - 93176
IT PROJECT MANAGER FOR SMART AGRITECH SOLUTION AB - 133678
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 183631
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 184442
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 185425
contract researcher F/H LCA of agricultural systems producing biogas by methanization - 1601667
IT PROJECT MANAGER FOR SMART AGRITECH SOLUTION AB - 1640947
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 1688238
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 1689049
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 1690032
Byggrådgivare till Hushållningssällskapet Kalmar Kronoberg Blekinge - 1738752
Teamledare Frukt och Grönt - 1779897
Teamledare Frukt och Grönt - 1849509
Trädgårdsarbetare - 1852652
Djurskötare till grisuppfödning - 1876933
Parkarbetare - säsong i Brålanda/Frändefors - 1878072
Parkarbetare - säsong i Vänersborg - 1878076
Park- och renhållningsarbetare - 1880092
Projektmedarbetare inom vattenvård - 1880872
Sommarjobb! PARKAVDELNINGEN - 1896630
Säsongsanställning inom Utemiljö hos Pema Partner i Linköping - 1897276
Sommarjobb, Yttre förvaltning - 1902292
Garden technician to the botanical garden - 1916001
Greenhouse assistant - 1929073
Church caretaker/cemetery worker - 1936355
Care workers for season 2025 Helsingborg - 1937803
Gardener to Crafttech in northern Stockholm - 1958636
Qualified landscape worker M/F - 20456
Landscape worker M/F - 20760
Green space maintenance worker (M/F) - 30237
Landscape worker M/F - 88961
Landscape worker M/F - 89002
Medarbetare Äggproduktion - 1736333
Säsongsarbetare till Uppsalahem - 1851304
Vidingehem AB söker vikarierande gruppledare till Yttre miljö - 1878011
Kyrkogårdsarbetare - Säsong - 1888945
Gestionnaire DATA F/H - 1910484
Data f/h manager - 1910485
Seasonal workers soil management - 1924610
Site manager to Lantmännen Maskin in Kalmar - 1924860
Dayshift Operator - 1962562


--- Excluded Jobs ---
Agricultural Sales - Export Managers
Agro Logistics Manager M/F
Agro Logistics Manager
Agricultural workshop manager
Agricultural mechanic M/F
Landscape gardener M/F
Maintenance and New Works Technician M/F
Technician, Animal Research Facility [LKCMedicine]
Technician, Animal Research Facility [LKCMedicine]
LABORATORY ANIMAL
LABORATORY ANIMAL
Director of Poultry Operations M/F
Food Quality and Safety System Manager M/F
Head of the Digital Product Development Department M/F
Subsidiary Manager M/F
Subsidiary Manager M/F
Sole Accountant M/F
Workshop Manager 3*8 M/F
Head of the Digital Product Development Department M/F
Subsidiary Manager M/F
Subsidiary Manager M/F
Food Quality and Safety System Manager M/F
Advisor with a focus on robust primary production within Greppa Näringen
Doctoral student in beef production on natural pastures
Researchers - bioinformatics and adaptation of crops to climate change
Researchers with a focus on advanced analysis of fish behavior
Bath water technician for new assignment in Täby
Veterinarian with an interest in infectious diseases in poultry
Veterinarian with an interest in infectious diseases in poultry
Contingency manager with a focus on project management
Contingency manager with a focus on the development of forms of support
Contingency manager with a focus on project management
Post-doc position on the quality of the dead wood and dead-wood dependent organisms
Postdoc position in deadwood quality and saproxylic communities
Teacher in agricultural subjects - Komvux
Professor in Business Studies
Postdoc in agricultural water management
Doctoral position in modeling of plant-environment and plant-plant interactions
PhD in modelling plant-environment and plant-plant interactions
Committed and relationship-building production manager for Sydvatten
Water Equipment Maintenance Technician M/F
Responsable des Opérations H/F
University lecturer in plant ecology
Senior Lecturer/Associate Professor* in Plant Ecology
Development leader within Community Building
Doctoral student, Biology - plant pathology and resistance breeding
PhD student, Biology - Plant Pathology and Resistance Breeding
Acting supervisor in animal welfare
Animal welfare officer
Researcher in Bioinformatics and crop adaptation to climate change
Contingency manager with a focus on the development of forms of support
MARKETING MANAGER FOR KONVEX AB
Advisor with a focus on robust primary production within Greppa Näringen
Doctoral student in beef production on natural pastures
Researchers - bioinformatics and adaptation of crops to climate change
Researchers with a focus on advanced analysis of fish behavior
Bath water technician for new assignment in Täby
Veterinarian with an interest in infectious diseases in poultry
Veterinarian with an interest in infectious diseases in poultry
Contingency manager with a focus on project management
Contingency manager with a focus on the development of forms of support
Contingency manager with a focus on project management
Post-doc position on the quality of the dead wood and dead-wood dependent organisms
Postdoc position in deadwood quality and saproxylic communities
Teacher in agricultural subjects - Komvux
Professor in Business Studies
Postdoc in agricultural water management
Doctoral position in modeling of plant-environment and plant-plant interactions
PhD in modelling plant-environment and plant-plant interactions
University lecturer in plant ecology
Senior Lecturer/Associate Professor* in Plant Ecology
Development leader within Community Building
Doctoral student, Biology - plant pathology and resistance breeding
PhD student, Biology - Plant Pathology and Resistance Breeding
Acting supervisor in animal welfare
Animal welfare officer
Researcher in Bioinformatics and crop adaptation to climate change
Contingency manager with a focus on the development of forms of support
MARKETING MANAGER FOR KONVEX AB
Technical Support Engineer
Naturbrukskolan Uddetorp is looking for a special teacher in mathematics
Researchers, Effect of temperature-induced germ line determination in plants
Animal welfare officer
Naturbrukskolan Uddetorp is looking for a cook
Coordinating Production Manager
Scientist in plant molecular biology and genetics
Natural School Uddetorp is looking for two student coaches
Biträdande rektor till Munkagårdsgymnasiet
Badvattentekniker till nytt uppdrag i Täby
Γεωπόνους Πωλήσεων - Export Managers
Forskare
DSS eller veterinär med chefsuppdrag för operationsenheten
Forskare, laboratoriestudier på torvjord
Postdoktor i biologi med fokus på fiskekologi och hydrologi
Butiks- och reservdelssäljare
Chef till Landsbygdsavdelningen, Funktionen för Djurskydd
Researcher Rural Development
Parkingenjör till Parkenheten
Djurvårdare/DSS/Veterinär med chefsuppdrag för vård-och operationsenheten
Butiks- och reservdelssäljare
Butiks- och reservdelssäljare
Växtodlingssäljare
Tekniker
Doktorand inom växtbiologi med fokus på cellväggens dynamik
Produktadministratör
Djurskyddshandläggare
Badvattentekniker till nytt uppdrag i Täby
Universitetslektor i skogspatologi
Senior Lecturer (Associate Professor) in Forest Pathology
Badvattentekniker till nytt uppdrag i Täby
Secodi Technicien itinérant H/F
BMA med uppdrag som enhetschef för Klinisk kemiska laboratoriet, SLU
Assistent till Kriscentrums skyddade boenden
Forskningsassistent
Berga söker en driftig växtodlings lärare
Kvalitetsansvarig Jord - Forma framtidens hållbara jordproduktion med oss!
Naturbrukslärare Växtodling
Rådgivare inom växtodling till kunskapsnav miljö och klimat
Postdoktor: Växthusgasutsläpp från jordar och metoder för att minska dem
Post doc  Mapping aquatic resources in a changing climate
Amanuens
Fastighetsskötare vid Institutionen för akvatiska resurser
Pedagog till S:t Hansgården
Handläggare för restaurering av vatten- och våtmarksmiljöer
Laboratoriechef vid institutionen för mark och miljö
Driftschef
Regional åtgärdssamordnare för fysiska åtgärder
Professor of Bioinformatics
CTO / Tech lead (H/F) REF 8209-JE
Butiks- och reservdelssäljare
Badvattentekniker till nytt uppdrag i Täby
Naturbruksskolan Sötåsen söker vikarierande lärare i svenska och engelska
PhD in Aquatic Ecology: Hydropower impacts on lake function & biodiversity
Business Analyst
MDM Developer | HT2025PM0106
Agronom/ biolog med fokus på kvalitetsstyrning (kvalitetskoordinator)
Medarbetare till enheten för jordbruk och livsmedelsföretagande
Medarbetare till enheten för jordbruk och livsmedelsföretagande
Postdoctoral researcher in dairy cattle grazing

In [ ]:
def filter_jobs(jobs, relevant_skills, occupations_data):
    accepted_by_skills , rejected_by_skills = filter_according_to_skills(jobs, relevant_skills)
    accepted_by_occupations, rejected_by_occupations = filter_according_to_occupations(accepted_by_skills, occupations_data)

    accepted = accepted_by_occupations
    rejected = rejected_by_skills | rejected_by_occupations

    return accepted, rejected

In [ ]:
accepted, rejected = filter_jobs(jobs_data, relevant_esco_skills, occupations_data)
print_filter_results(accepted, rejected)

Total number of accepted jobs: 268
Total number of rejected jobs: 1413
--- Accepted Jobs ---
MANAGER OF PRODUCTION - 1659
Farm Veterinarian - 2893
Veterinary - 3237
Senior Consultant Agriculture and Food Sector F/M - 6744
Versatile agricultural worker M/F - 28966
Poultry worker M/F - 29242
Poultry worker M/F - 29282
Agricultural Technician M/F - 30540
Land and Agricultural Estate Operations Director M/F - 31908
Day Maintenance Technician M/F - 32661
Agronomic R&D Technician | Agronomist - 45646
Agronomic R&D Technician | Agronomist - 45647
Agronomic R&D Technician | Agronomist - 45653
digital domain manager F/M - 52208
Agronomic R&D Technician | Agronomist - 61744
Day Maintenance Technician M/F - 63540
Versatile agricultural worker M/F - 71654
Industrial maintenance technician M/F Domaine Avicole - 72038
Chauffeur SPL* H/F - 73928
Poultry worker M/F - 74028
Agricultural mechanic M/F - 77751
Land and Agricultural Estate Operations Director M/F - 79161
Day Maintenance Technician M/F - 80351
Head of culture M/F - 82355
Day Maintenance Technician M/F - 91684
Station Manager - 92925
Veterinarian | Scientific Officer - 100780
Plant Innovation Manager F/M - 101775
Versatile agricultural worker - Animal worker M/F - 104496
Day Maintenance Technician M/F - 109562
Poultry worker M/F - 111027
Chauffeur SPL* H/F - 111073
Day Maintenance Technician M/F - 114191
Sales manager north, Väktodling - 123970
Expert/project manager in milk for sustainable animal production - 134508
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 141059
Administrators and advisors with a focus on farm animals - 145804
Agricultural adviser to the Councilors in Sjuhärad - 151290
Business manager for the new center for sustainable primary production - 153865
Farm worker/excavator - 156338
Summer job 2025;     Tractor driver for Widegrens Gård on Gotland - 156728
Tractor and machine operator for Widegrens Gård on Gotland - 156744
Animal care employee or animal care assistant (f/m/d) - 178509
Syngenta Group China Scientist - 184552
Animal welfare officer - 184576
Senior Consultant Agriculture and Food Sector F/M - 1526963
digital domain manager F/M - 1565152
Plant Innovation Manager F/M - 1609775
Sales manager north, Väktodling - 1631314
Expert/project manager in milk for sustainable animal production - 1641777
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 1647466
Administrators and advisors with a focus on farm animals - 1652211
Agricultural adviser to the Councilors in Sjuhärad - 1657697
Business manager for the new center for sustainable primary production - 1660272
Farm worker/excavator - 1662745
Summer Job 2025;     Tractor Driver For Widegrens Gård On Gotland - 1663135
Tractor and Machine Operator for Widegrens Gård on Gotland - 1663151
Syngenta Group China Scientist - 1689159
Animal welfare officer - 1689183
PLANT PRODUCTION FARMER (XANTHI) - 1695147
Training to become a cattle farming specialist (m/f/d) - 1697286
Technical assistant (m/f/d) breeding garden - 1698582
Application expert - 1702378
Operations manager SLU Lanna Property - 1702404
Substitute Cultivation coordinator/project manager - 1702872
Naturbrukskolan Uddetorp is looking for agricultural operations personnel - 1703236
Work with plant protection - three services in our socially important business - 1705490
Agricultural adviser to the Councilors in Sjuhärad - 1706977
Plant cultivation advisor to the Housekeeping Society Kalmar Kronoberg Blekinge - 1708081
Plant cultivation adviser to the Housekeeping Society Kalmar Kronoberg Blekinge - 1717705
Kundansvarig till Biototal Group i Skåne - 1725773
Kundansvarig till Biototal med arbetsområde Gävle med omnejd - 1736520
Responsable de pôle installation en agriculture (F/H) - 1743589
Herdenmanager m/w/d - 1745044
Gärtner*in (m/w/d) mit Fachrichtung Gemüsebau - 1746457
Djurskyddshandläggare med fokus på lantbrukets djur - 1749919
Stalltekniker - 1752303
Postdoc - Plant breeding towards nutritional quality in cereals - 1752439
Vi söker lantbruksekonomer och redovisningskonsulter - 1756129
Magasinier H/F - 1769732
Postdoktor i akvatisk ekologi - 1771536
Stadsbonde för kunskapshöjande odling inom staden - 1774835
Agraringenieur/ Anbauberater (m/w/d) - 1785933
Försökstekniker - 1787132
Produktionsledare/Driftledare med inriktning dikor och växtodling Svartsjö - 1788922
Vi söker lantbruksekonomer och redovisningskonsulter - 1793813
Βοηθός Παραγωγής Καλλωπιστικών Φυτών - 1800323
Agronomic R&D Researcher | Γεωπόνος - 1800329
Agronomic R&D Researcher | Γεωπόνος - 1800331
Trädgårdsmästare - 1818851
Technical Sales Representative - 1820244
Vi söker växtodlingsrådgivare till växtskyddscentralen i Landskrona - 1824076
ΓΕΩΠΟΝΟΣ ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ (ΞΑΝΘΗ) - 1826439
Agronomic R&D Specialist| Γεωπόνος - Λάρισα - 1826527
Agronomic R&D Specialist | Γεωπόνος - 1826529
Kundansvarig Uppsala - 1831136
Kundansvarig till Biototal Group i Skåne - 1831622
Agronomist - 1836155
Växtodlingsrådgivare Dalarna - 1840380
ΓΕΩΠΟΝΟΣ ΣΤΕΛΕΧΟΣ ΠΩΛΗΣΕΩΝ B2B - 1843233
Traktorförare Säsong 2025 - 1852203
Regionchef - 1854335
Driftledare Växtodling - 1856862
Εργασία σε Παραγωγή Καλλωπιστικών Φυτών - 1860660
Mécanicien agricole H/F - 1865627
Maraîcher H/F - 1867000
Sales intern (praktikant) - 1869435
Trädgård och markskötsel på AstraZeneca i Mölndal - 1878009
Utredare, inriktning  ekonomisk modellering och miljöeffekter av pesticider - 1880590
Traktorförare Säsong 2025 - 1880592
Säsongsarbetare till Vattenenheten - 1899018
Vi söker två agronomer eller lantmästare med jordbruksföretaget i fokus - 1899684
Agronomic R&D Specialist| Γεωπόνος - Κρήτη - 1906893
Horticultural Specialist till Swegreen - 1914224
Head of Department Nature and Water Department - 1915936
PhD Student in Plant Genetics and Breeding - 1924199
Nursery school to Billbäcks Nursery - 1926738
Research Assistant - 1938940
Agronomist - Horticulture Officer - 1940197
Versatile- animal agricultural worker M/F - 1942032
Plant engineering consultant - 1947969
PhD student position in land sector sustainability transitions - 1955393
Postdoctoral fellow in stock assessment - 2768666
Farm workers farmer, plant cultivation, soil, forest, animals - 2772113
Data H/F strategy project manager - 2786662
Caviste H/F - 22777
Automated Installations Driver M/F - 31431
IT Service Manager M/F - 57818
IT Service Manager M/F - 59176
Day Maintenance Technician M/F - 61220
Quality Facilitator M/F - 63570
Quality Facilitator M/F - 67959
Experienced wine worker (M/F) - 72877
Poultry worker M/F - 73969
Automated Installations Driver M/F - 78711
Caviste H/F - 83448
Foreman, Agricultural machinery - 117800
Property manager - 148201
Stable technician - 159328
IT Service Manager M/F - 1567924
Foreman, Agricultural machinery - 1625144
Property manager - 1654608
Stable technician - 1665735
Training as a cattle carer (m/f/d) specializing in cattle husbandry - 1697284
Training to become a cattle carer (m/f/d) - 1697285
Training as an animal farmer (m/f/d) specializing in cattle farming - 1697296
AGRARBETRIEBSWIRTIN/AGRARBETRIEBSWIRT (M/W/D) - 1698913
Zookeeper milk - 1702319
Pig keeper - 1709656
Vocational teachers in machine and natural use - 1713772
Gårdsansvarig - 1739844
Phd position within Sustainable Feed for Poultry and Pigs - 1751148
Postdoktor - Växtförädling för förbättrad näringskvalitet i spannmål - 1751994
Är du vår nästa maskinförare? Arbeta med modern utrustning i Vinslöv! - 1772492
Östergårds Grönsaker söker maskinförare! - 1774418
Försökstekniker till Sandbygård - 1776420
Senior Farm Sustainability Specialist - Viby, Stockholm or Düsseldorf. Remote working is possible. - 1780515
Är du vår nästa maskinförare? Arbeta med modern utrustning i Vinslöv! - 1788723
Växthusarbetare till food tech-bolag - 1791866
Växthusarbetare till food tech-bolag - 1792086
Maskinförare till ledande lantbruk i Vinslöv! - 1794245
Växthusarbetare till food tech-bolag (deltid) - 1809849
Växthusarbetare till food tech-bolag (deltid) - 1813715
Är du vår nästa maskinförare? Arbeta med modern utrustning i Vinslöv! - 1817157
Redovisningskonsult med avdelningsansvar - 1819381
Field staff wanted for field-based forest research during season 2025 - 1819635
Jobb för maskinförare - sök nu! - 1819918
Försökstekniker till Borgeby/Helgegården - 1823589
Försökstekniker till Borgeby/Helgegården - 1823755
Jobb för maskinförare - sök nu! - 1824383
Östergårds Grönsaker söker maskinförare! - 1824791
Jobb för maskinförare - sök nu! - 1835897
Försöksassistent - 1841619
Maskinförare växtodling - 1853395
Medarbetare till Christinelunds Gård - 1854356
Lantbrukare med huvudansvar för jordbruk och djurhållning - 1854878
Chef till funktionen Jordbrukarstöd - 1870403
Maskinförare,Lantarbetare Öjeby Gård - 1879631
DATA ANALYST F/H - 1887173
Avbytare Växa Sverige Laholm - 1889800
Betriebsleiter (m/w/d) im Obstbau - 1912288
Employees plant cultivation attempts - 1923021
Researchers in ecosystem services in strip cultivation - 1923458
Seasonal employee for organic vegetable cultivation on southern Gotland - 1932996
Market gardener H/F - 1943093
Summer job: substitute as a city farmer! - 2777019
Doctorant F/H Measuring brain microstructure through myelin content modelling in neurodegenerative diseases - 8578
SILO Storekeeper M/F - 25850
Landscape mason M/F - Temporary - Cluses - 28848
Landscape mason M/F - Temporary - Magland - 28943
Landscape mason M/F - CDI Sallanches - 28944
Landscape mason M/F - Temporary - Sallanches - 28990
Landscape mason M/F - CDI Magland - 28991
Växa is looking for an Expert in sustainability - 123574
Accounting consultant to Rådgivarna in Sjuhärad - 156301
Driftmaskinist - 185137
Doctorant F/H Measuring brain microstructure through myelin content modelling in neurodegenerative diseases - 1528797
Växa is looking for an Expert in sustainability - 1630918
Accounting Consultant to the advisers in Sjuhärad - 1662708
Driftmaskinist - 1689744
Pig production foreman - 1709715
Lantbruksarbete med fokus på växtodling och maskiner - 1737387
Lantbruksarbetare för ekologisk odling av indiska grönsaker - 1751210
Agronom, Forslundagymnasiet - 1807209
Vi söker nu en engagerad och ansvarstagande Gårdsansvarig till våra gårdar! - 1807732
Gårdsansvarig - 1812660
Jordbruksverket söker säsongsanställda till växtskyddscentralerna! - 1819507
Växa Sverige söker Kokontrollexpert! - 1824439
Distriktssäljare till DeLaval - 1830961
Distriktssäljare till DeLaval - 1830962
Gårdsansvarig - 1830982
Distriktssäljare till DeLaval - 1830984
Distriktssäljare till DeLaval - 1831743
Distriktssäljare till DeLaval - 1856825
Distriktssäljare till DeLaval - 1857125
Distriktssäljare till DeLaval - 1857231
Distriktssäljare till DeLaval - 1857232
Distriktssäljare i Skåne - 1857405
Farmer as a stable manager "Herdsman/Herdswoman" m/f/d - 1863420
Driftledare Lantbruk Öjeby Gård - 1879498
Samordnare för stadsnära odling - 1895320
Gårdsansvarig - 1899103
Trädgårdsmedarbetare kort säsong - 1902760
Support Manager with knowledge of agriculture - Strengthen precision agriculture and field planning with Näsgård - 1913493
Plant protection officer nursery school to Billbäcks Nursery - 1927093
Machine driver plant cultivation - 1938990
Farmer as a stable manager "Herdsman/Herdswoman" m/f/d - 1947973
contract researcher F/H LCA of agricultural systems producing biogas by methanization - 93176
IT PROJECT MANAGER FOR SMART AGRITECH SOLUTION AB - 133678
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 183631
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 184442
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 185425
contract researcher F/H LCA of agricultural systems producing biogas by methanization - 1601667
IT PROJECT MANAGER FOR SMART AGRITECH SOLUTION AB - 1640947
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 1688238
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 1689049
Construction consultant to the Housekeeping Society Kalmar Kronoberg Blekinge - 1690032
Byggrådgivare till Hushållningssällskapet Kalmar Kronoberg Blekinge - 1738752
Teamledare Frukt och Grönt - 1779897
Teamledare Frukt och Grönt - 1849509
Trädgårdsarbetare - 1852652
Djurskötare till grisuppfödning - 1876933
Parkarbetare - säsong i Brålanda/Frändefors - 1878072
Parkarbetare - säsong i Vänersborg - 1878076
Park- och renhållningsarbetare - 1880092
Projektmedarbetare inom vattenvård - 1880872
Sommarjobb! PARKAVDELNINGEN - 1896630
Säsongsanställning inom Utemiljö hos Pema Partner i Linköping - 1897276
Sommarjobb, Yttre förvaltning - 1902292
Garden technician to the botanical garden - 1916001
Greenhouse assistant - 1929073
Church caretaker/cemetery worker - 1936355
Care workers for season 2025 Helsingborg - 1937803
Gardener to Crafttech in northern Stockholm - 1958636
Qualified landscape worker M/F - 20456
Landscape worker M/F - 20760
Green space maintenance worker (M/F) - 30237
Landscape worker M/F - 88961
Landscape worker M/F - 89002
Medarbetare Äggproduktion - 1736333
Säsongsarbetare till Uppsalahem - 1851304
Vidingehem AB söker vikarierande gruppledare till Yttre miljö - 1878011
Kyrkogårdsarbetare - Säsong - 1888945
Gestionnaire DATA F/H - 1910484
Data f/h manager - 1910485
Seasonal workers soil management - 1924610
Site manager to Lantmännen Maskin in Kalmar - 1924860
Dayshift Operator - 1962562


--- Excluded Jobs ---
DIGITAL TRANSFORMATION INNOVATION PROJECT MANAGER M/F
Technical Leader in boilermaking H/F
Sales consultant (m/f/d) agricultural and construction machinery
Production Team Leader 3*8 M/F
Responsable QSE H/F
Security Facilitator M/F
Water Operations Technician M/F
After-sales team leader M/F
Sales Representative
WAREHOUSE & CUSTOMER MANAGEMENT OFFICER (FARMER / FOOD TECHNOLOGIST)
Sales Engineer - Heat Pumps M/F
Poultry Sales Director M/F
Poultry Sales Director M/F
Technical IT Project Manager M/F
Technical IT Project Manager M/F
Water Operations Technician M/F
Infrastructure Project Manager M/F
Infrastructure Project Manager M/F
Head of the Sanitation Maintenance Department M/F
Sales Engineer - Heat Pumps M/F
Production Team Leader 3*8 M/F
After-sales service team leader M/F
Poultry Sales Director M/F
Data Scientist Agronome H/F
Technician for the VA unit
Deputy store manager 100% to Örebro
Trial & Project Manager
Trial & Project Manager
Project manager fisheries management
Secondary school teacher in agriculture - temporary position
Supervisor for production
Operating technician for the Swedish Tourist Association's property department in Norrb...
Senior Scientist with background in farm animal genetics
DIGITAL TRANSFORMATION INNOVATION PROJECT MANAGER M/F
Technical Leader in boilermaking H/F
Technical IT Project Manager M/F
Infrastructure Project Manager M/F
Technician for the VA unit
Deputy store manager 100% to Örebro
Trial & Project Manager
Trial & Project Manager
Project manager fisheries management
Secondary school teacher in agriculture - temporary position
Supervisor for production
Operating technician for the Swedish Tourist Association's property department in Norrb...
Senior Scientist with background in farm animal genetics
Administrator for the Ministry of Rural Affairs and Infrastructure
Technicien Maintenance Itinérant H/F
Chef d'Equipe H/F
Technicien Exploitation Eau H/F
Besiktningstekniker
Besiktningstekniker
Arbeta med att stärka krisberedskapen inom djurområdet
Säljande avelsrådgivare
MASTER THESIS Land management practices for FLAG emissions reduction and removals increase
Enhetschef till enheten för landsbygdsutveckling
Elevassistent
Chef Samhällsbyggnadsserviceförvaltningen
Skiftledare till produktionen
Vikarie Djurskötare
Chef de Projet Infrastructure H/F
INKÖPARE GRIS TILL SKÖVDE SLAKTERI
Chef de Projet Infrastructure H/F
Sachbearbeiter im Grunderwerb (w/m/d)
Technicien de Maintenance 3x8 H/F
Study Director /undersökningsledare
Doktorand i vattenkraftens påverkan på sjöars funktion och diversitet
Study Director /undersökningsledare
Länsveterinär till Länsstyrelsen Gävleborg
Biolog
Fiskehandläggare
Systemspecialist / Teknisk dokumenthantering till Stockholm
Utredare Havsplanering Konsekvensbedömning
Senior Data Sustainability Specialist - Viby, Stockholm, Düsseldorf, Nijkerk or Remote
AnimalOOO söker en UI/UX designer
Forskningsassistent
Study Director /undersökningsledare
ΓΕΩΠΟΝΟΣ ΠΩΛΗΤΗΣ
Vattenrådgivare
Djurskötare mjölkproduktion
LANTBRUKSARBETARE - VISLANDA
Fritidskonsulent Fiske, Fritid
Vattenrådgivare
Förman Mjölkproduktion
Πρακτική άσκηση Γεωπονίας
Work Force Management Senior Manager - H/F
Internrevisor för IP Sigill Frukt & Grönt sökes till Toppfrys
Sandvikengården söker en biträdande Gårdsföreståndare
Grönyteskötare till uppdrag i Staffanstorp
Grönyteskötare till uppdrag i Lund
Grönyteskötare till uppdrag i Lomma
Grönyteskötare till uppdrag i Burlöv kommun
Handläggare med ansvar för jakt- och viltvårdsfrågor
KMA-koordinator - Göteborg
Växtodlingsrådgivare
Financial administrator, LTV Faculty's Office
Operating technician to Häggeberg's waterworks
Operating technicians VA
Officer Fisheries follow -up unit
Green Superior to assignments in Burlöv Municipality
Greenish coaches for assignments in Lomma
GreenThe coach to assignment in Staffanstorp
Investigator The Field Control Unit
Holiday work at Lantmännen Unibake, Örebro
Carutier h / f
Agrifood production agent M/F
We are looking for quality lines for our factory in Kungshamn!
Agronomist to Statistics Sweden
GreenThe coach for assignments in Lund
Greenish coaches for assignments in Lomma
GreenThe coach to assignment in Staffanstorp
Postdoctoral inom Best Mans Analysis of Fish
Investigators in sea plans
Chief the project sap - OTC (F / H)
Proximity computer support technician - Le Mans (72) - F/H
F/H System Engineer
Executive Legal & Strategic Assistant
Digital project manager - Finance (F/H)
CDI Data Scientist Modelisation 2 postes (F/H/NB)
Technico-commercial H/F
ING MAINTENANCE TECHNICIAN PORT EQUIPMENT SPECIALIST
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Endowed Professor (Tenured) in Maritime Management
LABORATORY ANIMAL
TECHNICIAN-MARKETING
WESTERN GREECE SALES DEPARTMENT
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Regional Technical-Sales Engineer M/F
Installation Technicians
Installation Technicians
Installation Technicians
Technico-commercial H/F
Landscape team leader M/F
After-sales service technician M/F
Landscape team leader M/F
Agriculturalist
Deputy housekeeping manager m/f/d
Landscape team leader M/F
Skipper for Svensk Sjöentreprenad in Malmö
Project manager at the Rural Development Unit
Sales warehouse manager in agricultural products
Electrical Engineer
Research assistant
Are you our new water manager?
Are you our new water manager?
Systems engineer
Responsable Production H/F
Phd position within forage production, feeding and grazing
Skipper for Swedish sea contract in Malmö
Project manager at the Rural Development Unit
Sales warehouse manager in agricultural products
Electrical Engineer
Research assistant
Are you our new water manager?
Are you our new water manager?
Systems engineer
Phd position within forage production, feeding and grazing
EXPORT EXECUTIVE
Deputy housekeeping manager m/f/d
Head of unit for the unit for rural development
Environmental investigator specializing in water management for the City of Stockholm, temporary position

In [ ]:
a,b,c = analyze_job_result(accepted ,justified_keywords, occupations_data, job_title="Växthusarbetare till food tech-bolag")

--- Selected Job ---
{'description': 'Do you have a genuine interest in plants? Are you attracted '
                'by independent physical work in a lovely environment? Apply '
                "for a position as a greenhouse worker for one of Sweden's "
                'most exciting food tech companies. Your future challenge '
                'Agtira is an innovative food tech company that supplies and '
                'operates vegetable farms. Right now, the company is in a '
                'growth phase and will therefore start a new facility in '
                'Kramfors in early 2025. For this facility, we are now looking '
                'for greenhouse workers who want to be involved from the start '
                'to build up this exciting business. Within Agtira, we are a '
                'total of 31 people who are distributed across five different '
                'facilities in Sweden. We are a tightly knit team that works '
                'together to develop the urban farms of the future. We do this '
                'by offering our customers Farming as a Service. In the role '
                'of a greenhouse worker, you will be responsible for daily '
                'plant care, quality assurance and biological control. Tasks '
                'that occur are: Planting Weeding Pruning Harvesting cucumbers '
                'Packaging cucumbers Who you are We are looking for you as has '
                'a genuine interest in plants. You also need to have an eye '
                'for details and like independent and physical work. It is '
                'desirable that you have previous experience with growing '
                'plants as well as with greenhouse equipment and scissor '
                'lifts. Good knowledge of Swedish and English is a '
                'requirement. You are over 18 years old. About the '
                'companyAgtira is a food tech company that supplies and '
                'operates facilities for sustainable and profitable food '
                'production. By growing cucumbers, tomatoes, herbs and other '
                'vegetables directly adjacent to stores, we eliminate the '
                'transport route and ensure that consumers can eat fresh '
                'vegetables all year round. Our Farming-as-a-Service (FaaS) '
                'business model means that we build and operate a tailor-made '
                'facility for the products the customer wants. The customer '
                'buys his entire needs at fixed prices for a longer period, up '
                'to 15 years. Our facilities are currently located in '
                'Härnösand, Sundsvall, Östersund and Skellefteå, as well as a '
                'new facility in Haninge that will open this autumn. Our '
                'ambition is to be a world leader in cultivation in urban '
                'environments and constantly develop both cultivation methods '
                'and software support. Click on the link to find out more! '
                'Agtira - Here-grown vegetables every day, all year round '
                '(youtube.com) Contact person If you have questions about the '
                'position, contact: Lisa Fagerström, recruitment consultant '
                'Cre8 Future, lisa.fagerstrom@cre8future.se , 076-8241789 Warm '
                'welcome with your application! Selection takes place on an '
                'ongoing basis, so submit your application as soon as '
                'possible. Last date for applications 6 January. Places '
                'Kramfors',
 'experience_level': None,
 'id': 1791866,
 'location': 'De nordiska länderna, Sweden',
 'location_code': 'SE',
 'nuts1': None,
 'nuts2': None,
 'nuts3': None,
 'occupations': ['http://data.europa.eu/esco/occupation/068370e0-9c27-4814-87d0-44fbb3140815',
                 'http://data.europa.eu/esco/occupation/2b48a4cd-2333-4abf-ac3e-6f63d6ed3663',
                 'http://data.europa.eu/esco/occupation/e3dc66de-99c7-4607-a82b-7244036d316d',
                 'http://data.europa.eu/esco/isco/C6111',
                 'http://data.europa.eu/esco/isco/C6113'],
 'organization': None,
 'skills': ['http://data.europa.eu/esco/skill/1177c6f5-09c5-4c35-873c-afd22d170ad3',
            'http://data.europa.eu/esco/skill/118796d8-28a3-4865-bcd0-d037f4abcc0f',
            'http://data.europa.eu/esco/skill/29a50780-f81b-429c-b410-7f23a492e19d',
            'http://data.europa.eu/esco/skill/2a2fa8e8-aaf3-4abf-a60b-af6415f1c6d4',
            'http://data.europa.eu/esco/skill/50f5e41d-7ce3-481b-aed7-ee9484545bc4',
            'http://data.europa.eu/esco/skill/68a8fc55-1755-40c0-ad3c-ef6371254159',
            'http://data.europa.eu/esco/skill/7ee51257-8947-4b69-9bdf-322baf0a6398'],
 'source': 'jobbland.se',
 'source_id': '18831430',
 'title': 'Växthusarbetare till food tech-bolag',
 'type': None,
 'upload_date': '2024-12-10'}


--- Similar Keywords ---
['crop production', 'biological control']


--- Similar Occupations Based on Fuzzy Match ---


--- Similar Occupations ---
Field crop and vegetable growers
Gardeners, horticultural and nursery growers

## extracting the skills

In [ ]:
def extract_skills (jobs):
  skills = {}
  for job in jobs.values():
    for skill_id in job.get('skills'):
      if skill_id not in skills:
        skills[skill_id] = [job['id']]
      else:
        skills[skill_id].append(job['id'])
  return skills

In [ ]:
skills = extract_skills(accepted)

pprint(skills)
print(f"total skills found: {len(skills)}")

{'http://data.europa.eu/esco/skill/00064735-8fad-454b-90c7-ed858cc993f2': [1788922],
 'http://data.europa.eu/esco/skill/001115fb-569f-4ee6-8381-c6807ef2527f': [123970,
                                                                           1631314,
                                                                           1725773,
                                                                           1736520,
                                                                           1752303,
                                                                           1831136,
                                                                           1831622,
                                                                           159328,
                                                                           1665735,
                                                                           123574,
                                                                           1630918,
                                                                           1897276],
 'http://data.europa.eu/esco/skill/00dd3271-077f-4a12-a958-e297fdd724ce': [77751,
                                                                           141059,
                                                                           1647466,
                                                                           117800,
                                                                           1625144,
                                                                           1851304],
 'http://data.europa.eu/esco/skill/015cd017-b146-4c9d-ab10-5dfca451c30a': [1932996],
 'http://data.europa.eu/esco/skill/02137a68-6860-45e8-8e4d-38db467bb8b6': [77751],
 'http://data.europa.eu/esco/skill/0232e2ee-5535-46e0-9c64-ea80c896c62f': [30237],
 'http://data.europa.eu/esco/skill/04012dd1-478d-4eec-9951-dd623bfe86ca': [2777019,
                                                                           1938990],
 'http://data.europa.eu/esco/skill/0450eaee-1a00-4622-8f4e-5356fce816d2': [32661,
                                                                           63540,
                                                                           80351,
                                                                           91684,
                                                                           109562,
                                                                           114191,
                                                                           63570,
                                                                           67959,
                                                                           30237],
 'http://data.europa.eu/esco/skill/048f04c9-83b1-48cd-9ac9-16a433695a61': [1743589],
 'http://data.europa.eu/esco/skill/04e08696-b62e-446c-9b53-3b48f9af0904': [1697286,
                                                                           1697284,
                                                                           1697285,
                                                                           1697296],
 'http://data.europa.eu/esco/skill/0539bd09-531a-4857-b739-cfd0316e4c65': [1751148],
 'http://data.europa.eu/esco/skill/054f26ab-cfdc-4077-883c-1c4c9e9b310a': [57818,
                                                                           59176,
                                                                           1567924],
 'http://data.europa.eu/esco/skill/0550431f-9c8b-4204-9c45-59bc5feacf06': [1887173,
                                                                           1807209],
 'http://data.europa.eu/esco/skill/055192dc-f16c-4855-835d-19cac6ff20aa': [184552,
                                                                           184576,
                                                                           1689159,
                                                                           1689183,
                                                                           1752439,
                                                                           1751148,
                                                                           1751994],
 'http://data.europa.eu/esco/skill/0612b3e9-5515-4233-af5e-07191b03c4ba': [1867000,
                                                                           1943093],
 'http://data.europa.eu/esco/skill/06b1f593-ac31-42ba-a2cd-5d86c755b416': [72877],
 'http://data.europa.eu/esco/skill/06bf62ec-3316-49b7-989f-a47fe61f8987': [1746457,
                                                                           1867000,
                                                                           1943093],
 'http://data.europa.eu/esco/skill/07846f2f-e182-4f94-a7c7-9fd2865c0dde': [29242,
                                                                           74028],
 'http://data.europa.eu/esco/skill/07862bb1-835a-4f14-9245-17717dc550a8': [77751,
                                                                           25850],
 'http://data.europa.eu/esco/skill/082967d4-b94c-4305-aa13-35a6aa8c5c7c': [141059,
                                                                           145804,
                                                                           153865,
                                                                           1647466,
                                                                           1652211,
                                                                           1660272,
                                                                           1703236,
                                                                           1705490,
                                                                           1736520,
                                                                           1787132,
                                                                           1831136,
                                                                           1713772,
                                                                           1870403,
                                                                           185137,
                                                                           1689744,
                                                                           1807209,
                                                                           1958636],
 'http://data.europa.eu/esco/skill/08dede9c-570a-462a-931a-481aef87fd6d': [1697286,
                                                                           1697284,
                                                                           1697285,
                                                                           1697296],
 'http://data.europa.eu/esco/skill/08e2ff26-88ff-47b5-9d37-d19ace01b075': [1899684],
 'http://data.europa.eu/esco/skill/095b0a0f-9b66-4e42-965e-d1c538a2986f': [1800323,
                                                                           1860660],
 'http://data.europa.eu/esco/skill/0af062de-eb43-41e9-9b96-249e2cd22d26': [1915936],
 'http://data.europa.eu/esco/skill/0b144726-21c2-46ed-8d13-c03d27f61604': [1695147,
                                                                           1843233,
                                                                           1702319],
 'http://data.europa.eu/esco/skill/0bfb44c7-c412-49ed-aab4-e33d0dd3b265': [123970,
                                                                           1631314,
                                                                           1913493],
 'http://data.europa.eu/esco/skill/0c1bbbd7-7827-4594-9254-a4b91cb8163f': [93176,
                                                                           1601667],
 'http://data.europa.eu/esco/skill/0c8f1351-d1fe-4542-89fe-b70729679c52': [30540],
 'http://data.europa.eu/esco/skill/0da516ee-e70e-4384-be13-f5ff80be8127': [6744,
                                                                           1526963,
                                                                           1708081,
                                                                           1717705,
                                                                           1818851,
                                                                           1820244,
                                                                           1840380,
                                                                           1843233,
                                                                           156301,
                                                                           1662708,
                                                                           1913493,
                                                                           1849509],
 'http://data.europa.eu/esco/skill/0e21e183-e787-4f23-a240-93b416c088c2': [1836155],
 'http://data.europa.eu/esco/skill/0e3493f4-0cad-4fbc-8e02-025f169b8114': [1807209],
 'http://data.europa.eu/esco/skill/0e9fbf47-0cec-4d82-97f9-12a3334819fe': [1870403],
 'http://data.europa.eu/esco/skill/0ebcef42-ad74-438d-b435-87fd734b4d72': [72877],
 'http://data.europa.eu/esco/skill/0ee7b0d6-db98-4785-9948-f2ef415d155a': [6744,
                                                                           1526963],
 'http://data.europa.eu/esco/skill/0ee94c0a-3716-494a-95a2-dcbab9e58be2': [1895320],
 'http://data.europa.eu/esco/skill/0ee9e985-0ee5-4a73-8a12-78b53b261bb2': [92925,
                                                                           123574,
                                                                           1630918,
                                                                           1913493],
 'http://data.europa.eu/esco/skill/1063b061-329e-4212-8db4-ab936dc60efc': [1880590],
 'http://data.europa.eu/esco/skill/113b4428-0a31-4199-8496-070af7854b91': [123970,
                                                                           1631314,
                                                                           1895320,
                                                                           1880092,
                                                                           1937803,
                                                                           1958636,
                                                                           1924860],
 'http://data.europa.eu/esco/skill/114a79ef-1e62-475b-a862-954f5b4cca20': [1878009,
                                                                           1902292,
                                                                           1916001],
 'http://data.europa.eu/esco/skill/1177c6f5-09c5-4c35-873c-afd22d170ad3': [1785933,
                                                                           1791866,
                                                                           1792086,
                                                                           1809849,
                                                                           1813715],
 'http://data.europa.eu/esco/skill/118796d8-28a3-4865-bcd0-d037f4abcc0f': [1914224,
                                                                           1791866,
                                                                           1792086,
                                                                           1809849,
                                                                           1813715,
                                                                           1929073],
 'http://data.europa.eu/esco/skill/123cf7c5-6a3b-419d-be4f-49a6cc020f9f': [141059,
                                                                           1647466,
                                                                           1703236],
 'http://data.europa.eu/esco/skill/12c7b323-d870-4f5b-9d7d-d9f525206d77': [1787132,
                                                                           1940197,
                                                                           185137,
                                                                           1689744,
                                                                           1807732],
 'http://data.europa.eu/esco/skill/13bf8e76-044a-43c3-9924-ee6d99b50a9f': [22777,
                                                                           83448],
 'http://data.europa.eu/esco/skill/13d96098-2ff0-46b8-b326-b7c0e18cc1f1': [1914224,
                                                                           1751148],
 'http://data.europa.eu/esco/skill/144aba2f-dddd-41bc-b519-0ea6d51bcd6b': [1947969],
 'http://data.europa.eu/esco/skill/14832d87-2f2f-4895-b290-e4760ebae42a': [1772492,
                                                                           1774418,
                                                                           1788723,
                                                                           1794245,
                                                                           1817157,
                                                                           1819918,
                                                                           1824383,
                                                                           1824791,
                                                                           1835897],
 'http://data.europa.eu/esco/skill/1565b401-1754-4b07-8f1a-eb5869e64d95': [1751148],
 'http://data.europa.eu/esco/skill/15d76317-c71a-4fa2-aadc-2ecc34e627b7': [134508,
                                                                           141059,
                                                                           153865,
                                                                           184576,
                                                                           1641777,
                                                                           1647466,
                                                                           1660272,
                                                                           1689183,
                                                                           1703236,
                                                                           1705490,
                                                                           1708081,
                                                                           1717705,
                                                                           1745044,
                                                                           1746457,
                                                                           1843233,
                                                                           1709656,
                                                                           1854878,
                                                                           1870403,
                                                                           1709715,
                                                                           1863420,
                                                                           1947973],
 'http://data.europa.eu/esco/skill/15e87c59-dd3f-4b72-a404-367cb0047eae': [1702872],
 'http://data.europa.eu/esco/skill/171eee55-19b9-46d6-aded-33193ba8ccf1': [1869435],
 'http://data.europa.eu/esco/skill/1835a7c1-600e-4b16-a0af-fb4f7d8d77b9': [1705490],
 'http://data.europa.eu/esco/skill/189777b9-6e95-4f76-b8db-f8e0f0477bc6': [82355,
                                                                           1836155,
                                                                           2777019,
                                                                           1888945],
 'http://data.europa.eu/esco/skill/18a5e674-550e-4fdf-98e9-df4584e2869c': [141059,
                                                                           1647466,
                                                                           1703236,
                                                                           1841619,
                                                                           1709715,
                                                                           1751210,
                                                                           1852652],
 'http://data.europa.eu/esco/skill/19858dd3-a5fe-4855-b644-6ecfefd1c384': [1788922],
 'http://data.europa.eu/esco/skill/198f62a5-dadb-4653-80fe-0108e8af7cd3': [1819635],
 'http://data.europa.eu/esco/skill/199f7919-5114-41b6-b6a5-41e0e4896ec1': [45646,
                                                                           45647,
                                                                           45653,
                                                                           61744,
                                                                           73928,
                                                                           111073,
                                                                           1800329,
                                                                           1800331,
                                                                           1826527,
                                                                           1826529,
                                                                           1906893,
                                                                           57818,
                                                                           59176,
                                                                           159328,
                                                                           1567924,
                                                                           1665735,
                                                                           1709656,
                                                                           1739844,
                                                                           1887173,
                                                                           1709715,
                                                                           1779897,
                                                                           1896630,
                                                                           1897276],
 'http://data.europa.eu/esco/skill/19ae47ed-6368-448a-b237-4fd270fc6d4c': [1746457],
 'http://data.europa.eu/esco/skill/1a163b43-9826-426f-9bda-05133a9f4bf3': [134508,
                                                                           1641777],
 'http://data.europa.eu/esco/skill/1a4cc54f-1e53-442b-a6d2-1682dc8ef8f9': [123970,
                                                                           1631314,
                                                                           117800,
                                                                           1625144],
 'http://data.europa.eu/esco/skill/1a6c7e0d-fc13-41d7-a5c0-8ca00606de89': [1912288],
 'http://data.europa.eu/esco/skill/1b957e3d-0017-42b0-9bfe-49a1cdd31de7': [1743589],
 'http://data.europa.eu/esco/skill/1c70f577-4c90-4fa9-9fc8-ac594c19dd52': [2772113],
 'http://data.europa.eu/esco/skill/1c9853ad-fad2-4d50-9fe3-6580d9e4d51e': [82355,
                                                                           1912288,
                                                                           1779897,
                                                                           1849509],
 'http://data.europa.eu/esco/skill/1ccde3e7-d2bb-4acb-bc8c-6831d7c13fc8': [93176,

In [ ]:
def filter_skills(skills, relevant_esco_skills):
  filtered_skills = {}
  for skill_id, job_ids in skills.items():
    if skill_id in relevant_esco_skills:
      filtered_skills[skill_id] = {'label': relevant_esco_skills.get(skill_id).get('skillLabel'), 'job_count': len(job_ids), 'job_ids': job_ids }
  return filtered_skills

skill_dict = filter_skills(skills, relevant_esco_skills)
pprint(skill_dict)
print(f"total of {len(skill_dict)} relevant skills")

{'http://data.europa.eu/esco/skill/00dd3271-077f-4a12-a958-e297fdd724ce': {'job_count': 6,
                                                                           'job_ids': [77751,
                                                                                       141059,
                                                                                       1647466,
                                                                                       117800,
                                                                                       1625144,
                                                                                       1851304],
                                                                           'label': 'operate '
                                                                                    'agricultural '
                                                                                    'machinery'},
 'http://data.europa.eu/esco/skill/0612b3e9-5515-4233-af5e-07191b03c4ba': {'job_count': 2,
                                                                           'job_ids': [1867000,
                                                                                       1943093],
                                                                           'label': 'monitor '
                                                                                    'crops'},
 'http://data.europa.eu/esco/skill/06b1f593-ac31-42ba-a2cd-5d86c755b416': {'job_count': 1,
                                                                           'job_ids': [72877],
                                                                           'label': 'harvest '
                                                                                    'grapes'},
 'http://data.europa.eu/esco/skill/07846f2f-e182-4f94-a7c7-9fd2865c0dde': {'job_count': 2,
                                                                           'job_ids': [29242,
                                                                                       74028],
                                                                           'label': 'insert '
                                                                                    'semen'},
 'http://data.europa.eu/esco/skill/07862bb1-835a-4f14-9245-17717dc550a8': {'job_count': 2,
                                                                           'job_ids': [77751,
                                                                                       25850],
                                                                           'label': 'technical '
                                                                                    'equipment '
                                                                                    'for '
                                                                                    'crop '
                                                                                    'production'},
 'http://data.europa.eu/esco/skill/08dede9c-570a-462a-931a-481aef87fd6d': {'job_count': 4,
                                                                           'job_ids': [1697286,
                                                                                       1697284,
                                                                                       1697285,
                                                                                       1697296],
                                                                           'label': 'livestock '
                                                                                    'reproduction'},
 'http://data.europa.eu/esco/skill/0e9fbf47-0cec-4d82-97f9-12a3334819fe': {'job_count': 1,
                                                                           'job_ids': [1870403],
                                                                           'label': 'control '
                                                                                    'animal '
                                                                                    'movement'},
 'http://data.europa.eu/esco/skill/118796d8-28a3-4865-bcd0-d037f4abcc0f': {'job_count': 6,
                                                                           'job_ids': [1914224,
                                                                                       1791866,
                                                                                       1792086,
                                                                                       1809849,
                                                                                       1813715,
                                                                                       1929073],
                                                                           'label': 'coordinate '
                                                                                    'greenhouse '
                                                                                    'environment'},
 'http://data.europa.eu/esco/skill/12c7b323-d870-4f5b-9d7d-d9f525206d77': {'job_count': 5,
                                                                           'job_ids': [1787132,
                                                                                       1940197,
                                                                                       185137,
                                                                                       1689744,
                                                                                       1807732],
                                                                           'label': 'production '
                                                                                    'processes'},
 'http://data.europa.eu/esco/skill/13bf8e76-044a-43c3-9924-ee6d99b50a9f': {'job_count': 2,
                                                                           'job_ids': [22777,
                                                                                       83448],
                                                                           'label': 'wine '
                                                                                    'characteristics'},
 'http://data.europa.eu/esco/skill/18a5e674-550e-4fdf-98e9-df4584e2869c': {'job_count': 7,
                                                                           'job_ids': [141059,
                                                                                       1647466,
                                                                                       1703236,
                                                                                       1841619,
                                                                                       1709715,
                                                                                       1751210,
                                                                                       1852652],
                                                                           'label': 'assign '
                                                                                    'duties '
                                                                                    'to '
                                                                                    'agriculture '
                                                                                    'workers'},
 'http://data.europa.eu/esco/skill/1c9853ad-fad2-4d50-9fe3-6580d9e4d51e': {'job_count': 4,
                                                                           'job_ids': [82355,
                                                                                       1912288,
                                                                                       1779897,
                                                                                       1849509],
                                                                           'label': 'supervise '
                                                                                    'fruit '
                                                                                    'production '
                                                                                    'teams'},
 'http://data.europa.eu/esco/skill/20a8fe89-d4eb-4698-8521-8881c13377e0': {'job_count': 1,
                                                                           'job_ids': [1824076],
                                                                           'label': 'interact '
                                                                                    'professionally '
                                                                                    'in '
                                                                                    'research '
                                                                                    'and '
                                                                                    'professional '
                                                                                    'environments'},
 'http://data.europa.eu/esco/skill/24783286-361a-44db-b0f1-aaabe35aef5d': {'job_count': 3,
                                                                           'job_ids': [22777,
                                                                                       72877,
                                                                                       83448],
                                                                           'label': 'manage '
                                                                                    'wine '
                                                                                    'production'},
 'http://data.europa.eu/esco/skill/263782c1-c65d-458a-ae67-8526ccf214f5': {'job_count': 2,
                                                                           'job_ids': [1887173,
                                                                                       1912288],
                                                                           'label': 'manage '
                                                                                    'agricultural '
                                                                                    'staff'},
 'http://data.europa.eu/esco/skill/2879557e-7c79-4f58-b076-99505ef34918': {'job_count': 2,
                                                                           'job_ids': [1752303,
                                                                                       1751148],
                                                                           'label': 'handle '
                                                                                    'pigs'},
 'http://data.europa.eu/esco/skill/29d1a8b4-608b-4152-987a-232605e3fb49': {'job_count': 2,
                                                                           'job_ids': [1739844,
                                                                                       1924610],
                                                                           'label': 'maintain '
                                                                                    'the '
                                                                                    'farm'},
 'http://data.europa.eu/esco/skill/2a58e994-74b9-4211-85ac-cfb409a9b667': {'job_count': 4,
                                                                           'job_ids': [1924199,
                                                                                       1807209,
                                                                                       1902760,
                                                                                       20456],
                                                                           'label': 'botany'},
 'http://data.europa.eu/esco/skill/2de4572a-4724-4f76-afc2-72a568a264ac': {'job_count': 9,
                                                                           'job_ids': [1772492,
                                                                                       1774418,
                                                                                       1788723,
                                                                                       1794245,
                                                                                       1817157,
                                                                                       1819918,
                                                                                       1824383,
                                                                                       1824791,
                                                                                       1835897],
                                                                           'label': 'speak '
                                                                                    'different '
                                                                                    'languages'},
 'http://data.europa.eu/esco/skill/2e4e8114-e579-453d-918e-b0262818ab76': {'job_count': 35,
                                                                           'job_ids': [32661,
                                                                                       52208,
                                                                                       63540,
                                                                                       80351,
                                                                                       91684,
                                                                                       109562,
                                                                                       114191,
                                                                                       1565152,
                                                                                       1698582,
                                                                                       1787132,
                                                                                       1852203,
                                                                                       1867000,
                                                                                       1880592,
                                                                                       22777,
                                                                                       31431,
                                                                                       57818,
                                                                                       59176,
                                                                                       61220,
                                                                                       63570,
                                                                                       67959,
                                                                                       78711,
                                                                                       83448,
                                                                                       1567924,
                                                                                       1739844,
                                                                                       1772492,
                                                                                       1774418,
                                                                                       1788723,
                                                                                       1794245,
                                                                                       1817157,
                                                                                       1819918,
                                                                                       1824383,
                                                                                       1824791,
                                                                                       1835897,
                                                                                       1943093,
                                                                                       1751210],
                                                                           'label': 'harvest '
                                                                                    'crop'},
 'http://data.europa.eu/esco/skill/2f05ac16-ecf0-4830-b3fb-f973f9d6c0db': {'job_count': 3,
                                                                           'job_ids': [133678,
                                                                                       1640947,
                                                                                       1876933],
                                                                           'label': 'breed '
                                                                                    'pigs'},
 'http://data.europa.eu/esco/skill/31eede0c-9dac-49b8-b61b-1f9f22e79e1e': {'job_count': 1,
                                                                           'job_ids': [1915936],
                                                                           'label': 'animal '
                                                                                    'hunting'},
 'http://data.europa.eu/esco/skill/3419fac9-575d-4492-a018-edff6f4dae26': {'job_count': 3,
                                                                           'job_ids': [1867000,
                                                                                       1880590,
                                                                                       1943093],
                                                                           'label': 'environmental '
                                                                                    'legislation '
                                                                                    'in '
                                                                                    'agriculture '
                                                                                    'and '
                                                                                    'forestry'},
 'http://data.europa.eu/esco/skill/35f1dcdc-577f-46c6-96d9-6c7a64501de9': {'job_count': 6,
                                                                           'job_ids': [1739844,
                                                                                       1772492,
                                                                                       1774418,
                                                                                       1788723,
                                                                                       1794245,
                                                                                       1835897],
                                                                           'label': 'laboratory '
                                                                                    'equipment'},
 'http://data.europa.eu/esco/skill/39f67488-cfd3-4370-8d7e-da98163102d9': {'job_count': 1,
                                                                           'job_ids': [2768666],

# Filtering the skills

1716 skills are returned and most of them are not relevant to agriculture. So we need to filter them

We import the csv file with all the optional and essential skills related to agriculture and taking the skills column which contains the skills (the file was created using the turtle version of ESCO data and a simple sparql query to find all the skills that are optionally or essentially connected to the occupations related to agriculture - it contains 855 skills)

In [ ]:
sorted_skills = sorted(skill_dict.items(), key=lambda item: item[1]['job_count'], reverse=True)

print("--- Relevant Skills sorted by job_count (Descending) ---")
for skill_id, skill_info in sorted_skills:
    print(f"Skill ID: {skill_id}, Label: {skill_info['label']}, Job Count: {skill_info['job_count']}, Job IDs: {skill_info['job_ids']}")

--- Relevant Skills sorted by job_count (Descending) ---
Skill ID: http://data.europa.eu/esco/skill/2e4e8114-e579-453d-918e-b0262818ab76, Label: harvest crop, Job Count: 35, Job IDs: [32661, 52208, 63540, 80351, 91684, 109562, 114191, 1565152, 1698582, 1787132, 1852203, 1867000, 1880592, 22777, 31431, 57818, 59176, 61220, 63570, 67959, 78711, 83448, 1567924, 1739844, 1772492, 1774418, 1788723, 1794245, 1817157, 1819918, 1824383, 1824791, 1835897, 1943093, 1751210]
Skill ID: http://data.europa.eu/esco/skill/4ca83b9d-afa0-49f8-b7af-e4e6a42ad299, Label: crop production principles, Job Count: 35, Job IDs: [141059, 151290, 156338, 156744, 184552, 1647466, 1657697, 1662745, 1663151, 1689159, 1702404, 1703236, 1706977, 1708081, 1756129, 1788922, 1793813, 1856862, 159328, 1665735, 1702319, 1709656, 1713772, 1819381, 1853395, 1854356, 1854878, 123574, 156301, 1630918, 1662708, 1709715, 1751210, 1807209, 1736333]
Skill ID: http://data.europa.eu/esco/skill/c4b03a17-a93e-4a8e-9846-4c4d469d4001, Label: agroecology, Job Count: 29, Job IDs: [32661, 45646, 45647, 45653, 52208, 61744, 63540, 73928, 101775, 111073, 153865, 1565152, 1609775, 1660272, 1702872, 1717705, 1725773, 1736520, 1800329, 1800331, 1824076, 1826527, 1826529, 1831136, 1831622, 1869435, 1906893, 1926738, 1938940]
Skill ID: http://data.europa.eu/esco/skill/754de174-292f-4ddc-ae08-24b8fb8cff2e, Label: manage crop production, Job Count: 25, Job IDs: [82355, 92925, 123970, 145804, 156728, 156744, 1631314, 1652211, 1663135, 1663151, 1702404, 1705490, 1820244, 1852203, 1854335, 1940197, 1739844, 1870403, 1879631, 1737387, 1807209, 1812660, 1830982, 1899103, 1913493]
Skill ID: http://data.europa.eu/esco/skill/b47da85a-bfde-4012-a3b2-60be9f7ddcdc, Label: research improvement of crop yields, Job Count: 25, Job IDs: [156728, 156744, 184552, 1663135, 1663151, 1689159, 1708081, 1717705, 1820244, 1924199, 1772492, 1774418, 1776420, 1788723, 1794245, 1817157, 1819918, 1823589, 1823755, 1824383, 1824791, 1835897, 1841619, 1923458, 1932996]
Skill ID: http://data.europa.eu/esco/skill/5f95f9c9-30ee-4735-ab63-8045ec8f78f8, Label: agricultural equipment, Job Count: 24, Job IDs: [28966, 30540, 71654, 77751, 104496, 156728, 156744, 1663135, 1663151, 1865627, 1942032, 117800, 1625144, 1772492, 1774418, 1788723, 1794245, 1817157, 1819918, 1824383, 1824791, 1835897, 1841619, 1923021]
Skill ID: http://data.europa.eu/esco/skill/e1479957-1606-4dbd-90f7-4c46c615936c, Label: prepare planting area, Job Count: 21, Job IDs: [28966, 71654, 1746457, 1818851, 1852203, 1878009, 1880592, 1926738, 28848, 28943, 28944, 28990, 28991, 1927093, 1878072, 1878076, 1916001, 1936355, 1958636, 1878011, 1888945]
Skill ID: http://data.europa.eu/esco/skill/568e4759-c698-4879-a6c2-708b4e6a0dc7, Label: manage farm products, Job Count: 18, Job IDs: [2893, 3237, 100780, 134508, 184576, 1641777, 1689183, 1705490, 1717705, 1725773, 1736520, 1824076, 1831136, 1831622, 1840380, 1739844, 1853395, 1824439]
Skill ID: http://data.europa.eu/esco/skill/d3d99bf2-cdad-4bdf-acd3-c94d599c4808, Label: manage livestock, Job Count: 18, Job IDs: [29282, 32661, 63540, 80351, 91684, 109562, 111027, 114191, 1749919, 1788922, 31431, 61220, 63570, 67959, 73969, 78711, 1879631, 1879498]
Skill ID: http://data.europa.eu/esco/skill/496932f1-0b6b-4f73-9432-d95c7ddcd43b, Label: recruit employees, Job Count: 16, Job IDs: [141059, 1647466, 1703236, 1705490, 1769732, 1774835, 1788922, 1824076, 1899684, 148201, 1654608, 2777019, 1819507, 1896630, 1937803, 1736333]
Skill ID: http://data.europa.eu/esco/skill/a2b5dcf3-5b6a-453d-876c-cff540c0faf1, Label: CAD software, Job Count: 16, Job IDs: [1830961, 1830962, 1830984, 1831743, 1856825, 1857125, 1857231, 1857232, 1857405, 183631, 184442, 185425, 1688238, 1689049, 1690032, 1738752]
Skill ID: http://data.europa.eu/esco/skill/4bd422bb-6ea3-4161-a908-53c0f5a1bb00, Label: animal production science, Job Count: 13, Job IDs: [1659, 31908, 79161, 134508, 151290, 1641777, 1657697, 1706977, 1745044, 1840380, 1843233, 1698913, 1819381]
Skill ID: http://data.europa.eu/esco/skill/91a6da8d-24dc-4453-9821-de305864677c, Label: soil science, Job Count: 11, Job IDs: [184552, 1689159, 1878009, 2772113, 1819635, 1841619, 123574, 1630918, 1807209, 1902292, 20456]
Skill ID: http://data.europa.eu/esco/skill/5eafee30-f3b6-4cd6-baf8-517bb2f3d625, Label: agronomical production principles, Job Count: 10, Job IDs: [45646, 45647, 45653, 61744, 1702378, 1800329, 1800331, 1820244, 1826527, 1826529]
Skill ID: http://data.europa.eu/esco/skill/518779a6-ea5d-4e4b-8029-8bc90b5bcb92, Label: agricultural business management, Job Count: 10, Job IDs: [52208, 123970, 1565152, 1631314, 1702404, 57818, 59176, 1567924, 156301, 1662708]
Skill ID: http://data.europa.eu/esco/skill/97272b3e-d497-4420-893d-612b15d377d9, Label: e-agriculture, Job Count: 10, Job IDs: [72038, 184552, 1689159, 1697286, 1743589, 1914224, 1697284, 1697285, 1697296, 1713772]
Skill ID: http://data.europa.eu/esco/skill/ae6d655d-bbce-4701-ba04-d687cfa90eda, Label: safeguard biodiversity, Job Count: 10, Job IDs: [101775, 1609775, 1878009, 1899018, 1938940, 1955393, 1751148, 1923458, 1932996, 1880872]
Skill ID: http://data.europa.eu/esco/skill/798d427e-51b3-4cd4-8b24-1357015e9ae7, Label: optimise production, Job Count: 10, Job IDs: [1772492, 1774418, 1788723, 1794245, 1817157, 1819918, 1824383, 1824791, 1835897, 1913493]
Skill ID: http://data.europa.eu/esco/skill/70159320-b7f9-4d3e-9f00-99e0adf3f77e, Label: perform inspection analysis, Job Count: 9, Job IDs: [148201, 1654608, 183631, 184442, 185425, 1688238, 1689049, 1690032, 1738752]
Skill ID: http://data.europa.eu/esco/skill/2de4572a-4724-4f76-afc2-72a568a264ac, Label: speak different languages, Job Count: 9, Job IDs: [1772492, 1774418, 1788723, 1794245, 1817157, 1819918, 1824383, 1824791, 1835897]
Skill ID: http://data.europa.eu/esco/skill/edf6ed6b-bc24-4211-ae0f-6b5cb9de4437, Label: select livestock, Job Count: 7, Job IDs: [28966, 71654, 1695147, 1826439, 57818, 59176, 1567924]
Skill ID: http://data.europa.eu/esco/skill/18a5e674-550e-4fdf-98e9-df4584e2869c, Label: assign duties to agriculture workers, Job Count: 7, Job IDs: [141059, 1647466, 1703236, 1841619, 1709715, 1751210, 1852652]
Skill ID: http://data.europa.eu/esco/skill/609d6bb4-db16-4578-87fc-57b11a701cc2, Label: bioeconomy, Job Count: 7, Job IDs: [1880592, 1955393, 1841619, 1938990, 93176, 1601667, 1924860]
Skill ID: http://data.europa.eu/esco/skill/49212efd-acf0-4257-a011-e07c9e369ecf, Label: animal welfare legislation, Job Count: 7, Job IDs: [183631, 184442, 185425, 1688238, 1689049, 1690032, 1738752]
Skill ID: http://data.europa.eu/esco/skill/94812554-043f-4ffd-838e-583eccf3e297, Label: watering principles, Job Count: 6, Job IDs: [72038, 77751, 1880092, 1916001, 1936355, 1924610]
Skill ID: http://data.europa.eu/esco/skill/00dd3271-077f-4a12-a958-e297fdd724ce, Label: operate agricultural machinery, Job Count: 6, Job IDs: [77751, 141059, 1647466, 117800, 1625144, 1851304]
Skill ID: http://data.europa.eu/esco/skill/97725325-5287-4ebb-9f83-1ba2c38f465c, Label: produce sustainable products, Job Count: 6, Job IDs: [141059, 1647466, 1703236, 1752439, 1924199, 1923458]
Skill ID: http://data.europa.eu/esco/skill/118796d8-28a3-4865-bcd0-d037f4abcc0f, Label: coordinate greenhouse environment, Job Count: 6, Job IDs: [1914224, 1791866, 1792086, 1809849, 1813715, 1929073]
Skill ID: http://data.europa.eu/esco/skill/35f1dcdc-577f-46c6-96d9-6c7a64501de9, Label: laboratory equipment, Job Count: 6, Job IDs: [1739844, 1772492, 1774418, 1788723, 1794245, 1835897]
Skill ID: http://data.europa.eu/esco/skill/77f109c4-3107-4d2a-a512-5160ac103933, Label: analyse environmental data, Job Count: 5, Job IDs: [153865, 1660272, 1899018, 1841619, 1880872]
Skill ID: http://data.europa.eu/esco/skill/a6bbc19a-381c-4c60-a79a-41dea2d1a422, Label: drive agricultural machines, Job Count: 5, Job IDs: [156728, 156744, 1663135, 1663151, 1776420]
Skill ID: http://data.europa.eu/esco/skill/12c7b323-d870-4f5b-9d7d-d9f525206d77, Label: production processes, Job Count: 5, Job IDs: [1787132, 1940197, 185137, 1689744, 1807732]
Skill ID: http://data.europa.eu/esco/skill/68a8fc55-1755-40c0-ad3c-ef6371254159, Label: plant care products, Job Count: 5, Job IDs: [1791866, 1792086, 1809849, 1813715, 1852652]
Skill ID: http://data.europa.eu/esco/skill/b7cf2d84-6c43-4baa-98cf-816a27336701, Label: maintain gardening equipment, Job Count: 5, Job IDs: [1854878, 1852652, 1916001, 1936355, 20456]
Skill ID: http://data.europa.eu/esco/skill/51097602-8e4e-4830-8f35-d77afc713fc0, Label: prune hedges and trees, Job Count: 5, Job IDs: [1897276, 20456, 20760, 88961, 89002]
Skill ID: http://data.europa.eu/esco/skill/1c9853ad-fad2-4d50-9fe3-6580d9e4d51e, Label: supervise fruit production teams, Job Count: 4, Job IDs: [82355, 1912288, 1779897, 1849509]
Skill ID: http://data.europa.eu/esco/skill/08dede9c-570a-462a-931a-481aef87fd6d, Label: livestock reproduction, Job Count: 4, Job IDs: [1697286, 1697284, 1697285, 1697296]
Skill ID: http://data.europa.eu/esco/skill/8bdd25f8-4b6e-40fe-a2cf-c1badc594114, Label: geology, Job Count: 4, Job IDs: [1697286, 1697284, 1697285, 1697296]
Skill ID: http://data.europa.eu/esco/skill/691c7db6-bad8-4a09-a3c4-4bf799375a35, Label: sustainable agricultural production principles, Job Count: 4, Job IDs: [1705490, 1824076, 1899684, 1819507]
Skill ID: http://data.europa.eu/esco/skill/2a58e994-74b9-4211-85ac-cfb409a9b667, Label: botany, Job Count: 4, Job IDs: [1924199, 1807209, 1902760, 20456]
Skill ID: http://data.europa.eu/esco/skill/9531fe02-1e1f-4a36-95f7-a76a77cd4b8d, Label: consult with business clients, Job Count: 3, Job IDs: [6744, 1526963, 1962562]
Skill ID: http://data.europa.eu/esco/skill/912f7556-6b75-4d73-9658-4e710050199d, Label: apply animal hygiene practices, Job Count: 3, Job IDs: [28966, 71654, 104496]
Skill ID: http://data.europa.eu/esco/skill/be6eac29-bb46-492d-a511-2438fca420bd, Label: horticultural design, Job Count: 3, Job IDs: [1708081, 1717705, 1913493]
Skill ID: http://data.europa.eu/esco/skill/ecf9829d-e532-45cf-aaff-1dd1fb1c812b, Label: manage crop rotation, Job Count: 3, Job IDs: [1708081, 1717705, 1947969]
Skill ID: http://data.europa.eu/esco/skill/3419fac9-575d-4492-a018-edff6f4dae26, Label: environmental legislation in agriculture and forestry, Job Count: 3, Job IDs: [1867000, 1880590, 1943093]
Skill ID: http://data.europa.eu/esco/skill/d300a8db-f353-4acb-aa6e-9dc757daf1bf, Label: operate farm equipment, Job Count: 3, Job IDs: [2772113, 1879631, 1824439]
Skill ID: http://data.europa.eu/esco/skill/24783286-361a-44db-b0f1-aaabe35aef5d, Label: manage wine production, Job Count: 3, Job IDs: [22777, 72877, 83448]
Skill ID: http://data.europa.eu/esco/skill/c5f255ef-02d3-4ab0-a652-2bf055d1d493, Label: grow plants, Job Count: 3, Job IDs: [1819635, 1932996, 1879498]
Skill ID: http://data.europa.eu/esco/skill/2f05ac16-ecf0-4830-b3fb-f973f9d6c0db, Label: breed pigs, Job Count: 3, Job IDs: [133678, 1640947, 1876933]
Skill ID: http://data.europa.eu/esco/skill/07846f2f-e182-4f94-a7c7-9fd2865c0dde, Label: insert semen, Job Count: 2, Job IDs: [29242, 74028]
Skill ID: http://data.europa.eu/esco/skill/afdcb380-ef9f-4785-b877-cc551f035034, Label: agronomy, Job Count: 2, Job IDs: [31908, 79161]
Skill ID: http://data.europa.eu/esco/skill/6c8ed0d1-4fc9-41a6-9587-6dbc82cabfc3, Label: collection management, Job Count: 2, Job IDs: [52208, 1565152]
Skill ID: http://data.europa.eu/esco/skill/07862bb1-835a-4f14-9245-17717dc550a8, Label: technical equipment for crop production, Job Count: 2, Job IDs: [77751, 25850]
Skill ID: http://data.europa.eu/esco/skill/a8d24a95-47b3-4f88-92e7-06600bcd3612, Label: manage personal professional development, Job Count: 2, Job IDs: [178509, 1836155]
Skill ID: http://data.europa.eu/esco/skill/4e6cfb60-9579-4822-8a5e-424bc0c8835c, Label: animal welfare, Job Count: 2, Job IDs: [184576, 1689183]
Skill ID: http://data.europa.eu/esco/skill/fdc388ba-c8f4-4455-a55f-ffdf29b05f5f, Label: use agricultural information systems and databases, Job Count: 2, Job IDs: [1702404, 2786662]
Skill ID: http://data.europa.eu/esco/skill/3c82bd87-15f3-4628-a0ff-db396139ca3e, Label: interact safely with animals, Job Count: 2, Job IDs: [1749919, 73969]
Skill ID: http://data.europa.eu/esco/skill/2879557e-7c79-4f58-b076-99505ef34918, Label: handle pigs, Job Count: 2, Job IDs: [1752303, 1751148]
Skill ID: http://data.europa.eu/esco/skill/61bef658-d7f9-4759-b1b0-0f9cb3bc581a, Label: biotechnology, Job Count: 2, Job IDs: [1752439, 1751994]
Skill ID: http://data.europa.eu/esco/skill/c8f14c32-7f24-41bb-9e8f-b24d6fd3ca86, Label: follow production schedule, Job Count: 2, Job IDs: [1800323, 1860660]
Skill ID: http://data.europa.eu/esco/skill/0612b3e9-5515-4233-af5e-07191b03c4ba, Label: monitor crops, Job Count: 2, Job IDs: [1867000, 1943093]
Skill ID: http://data.europa.eu/esco/skill/9d3490b2-a0e6-415b-81a4-a3a4a63268b0, Label: maintain plant health, Job Count: 2, Job IDs: [1914224, 1751210]
Skill ID: http://data.europa.eu/esco/skill/6d043734-b8a7-40bd-8e7a-c873bf9e310b, Label: maintain breeding equipment, Job Count: 2, Job IDs: [1942032, 1807732]
Skill ID: http://data.europa.eu/esco/skill/13bf8e76-044a-43c3-9924-ee6d99b50a9f, Label: wine characteristics, Job Count: 2, Job IDs: [22777, 83448]
Skill ID: http://data.europa.eu/esco/skill/8853dc46-e29e-4c6e-ab9c-f2553f7b2b8f, Label: operate hand pruning equipment, Job Count: 2, Job IDs: [72877, 30237]
Skill ID: http://data.europa.eu/esco/skill/29d1a8b4-608b-4152-987a-232605e3fb49, Label: maintain the farm, Job Count: 2, Job IDs: [1739844, 1924610]
Skill ID: http://data.europa.eu/esco/skill/cd5efa8c-e44d-4cbc-91c6-796018dbed68, Label: perform project management, Job Count: 2, Job IDs: [1780515, 1895320]
Skill ID: http://data.europa.eu/esco/skill/263782c1-c65d-458a-ae67-8526ccf214f5, Label: manage agricultural staff, Job Count: 2, Job IDs: [1887173, 1912288]
Skill ID: http://data.europa.eu/esco/skill/4339176e-3acd-4f7f-a5d9-445bee3d23f2, Label: mathematics, Job Count: 2, Job IDs: [8578, 1528797]
Skill ID: http://data.europa.eu/esco/skill/4c6c52d6-f791-4202-b45a-96512ca5222e, Label: move animals, Job Count: 2, Job IDs: [1863420, 1947973]
Skill ID: http://data.europa.eu/esco/skill/a8f1c3cf-bd8b-4c85-80d3-c69955f6bd00, Label: pruning techniques, Job Count: 2, Job IDs: [1852652, 1958636]
Skill ID: http://data.europa.eu/esco/skill/cda471f8-e175-4340-8259-4636eff669f8, Label: control wine quality, Job Count: 2, Job IDs: [1910484, 1910485]
Skill ID: http://data.europa.eu/esco/skill/435d1751-8667-41ec-8b32-865b7cd3c684, Label: manage production enterprise, Job Count: 1, Job IDs: [1659]
Skill ID: http://data.europa.eu/esco/skill/b9f621b2-fecb-417c-98ca-802cbf0ba0b9, Label: store crops, Job Count: 1, Job IDs: [29242]
Skill ID: http://data.europa.eu/esco/skill/51754b8a-3e2c-4cc1-86e6-cf510d9c6fe4, Label: use personal protection equipment, Job Count: 1, Job IDs: [77751]
Skill ID: http://data.europa.eu/esco/skill/5d7e0ecb-350a-4a49-8e2d-1f1d9c98d43f, Label: advise on plant mineral nutrition, Job Count: 1, Job IDs: [1702378]
Skill ID: http://data.europa.eu/esco/skill/9d75efb9-0c77-4f86-b5e7-99100808564a, Label: pest control in plants, Job Count: 1, Job IDs: [1705490]
Skill ID: http://data.europa.eu/esco/skill/a7573f65-d00c-417f-b952-441ebaeed675, Label: create crop protection plans, Job Count: 1, Job IDs: [1705490]
Skill ID: http://data.europa.eu/esco/skill/74688c5d-2af1-4f7a-9d1c-00e808eaa1e6, Label: budgetary principles, Job Count: 1, Job IDs: [1743589]
Skill ID: http://data.europa.eu/esco/skill/aba1f05b-f312-47d8-be71-7c574134de8f, Label: advertising techniques, Job Count: 1, Job IDs: [1749919]
Skill ID: http://data.europa.eu/esco/skill/d4eeb8f1-50d2-4a62-a405-f5eeaeec7f52, Label: research livestock production, Job Count: 1, Job IDs: [1749919]
Skill ID: http://data.europa.eu/esco/skill/74e49482-75e8-4637-bdb1-fff868d02f7a, Label: scientific literature, Job Count: 1, Job IDs: [1771536]
Skill ID: http://data.europa.eu/esco/skill/dc57f705-75b6-4232-b531-1f020afa0364, Label: food and beverage industry, Job Count: 1, Job IDs: [1785933]
Skill ID: http://data.europa.eu/esco/skill/20a8fe89-d4eb-4698-8521-8881c13377e0, Label: interact professionally in research and professional environments, Job Count: 1, Job IDs: [1824076]
Skill ID: http://data.europa.eu/esco/skill/dc9a236c-c640-43c3-812f-269403591edb, Label: customer relationship management, Job Count: 1, Job IDs: [1869435]
Skill ID: http://data.europa.eu/esco/skill/ed3f3dba-3a35-4ed5-b113-67f4d10ef4c8, Label: scientific research methodology, Job Count: 1, Job IDs: [1880590]
Skill ID: http://data.europa.eu/esco/skill/f8460277-3c9a-4be4-b203-600a2a295f47, Label: plant disease control, Job Count: 1, Job IDs: [1914224]
Skill ID: http://data.europa.eu/esco/skill/31eede0c-9dac-49b8-b61b-1f9f22e79e1e, Label: animal hunting, Job Count: 1, Job IDs: [1915936]
Skill ID: http://data.europa.eu/esco/skill/c7cc6dc5-d56b-4323-8e5c-47c4022f615f, Label: quality assurance methodologies, Job Count: 1, Job IDs: [1940197]
Skill ID: http://data.europa.eu/esco/skill/ff64e9fc-36dd-4035-872a-83aa41dc1ad9, Label: communicate with a non-scientific audience, Job Count: 1, Job IDs: [1955393]
Skill ID: http://data.europa.eu/esco/skill/39f67488-cfd3-4370-8d7e-da98163102d9, Label: evaluate research activities, Job Count: 1, Job IDs: [2768666]
Skill ID: http://data.europa.eu/esco/skill/06b1f593-ac31-42ba-a2cd-5d86c755b416, Label: harvest grapes, Job Count: 1, Job IDs: [72877]
Skill ID: http://data.europa.eu/esco/skill/92d36561-e0ce-429e-a6ee-eeee17259953, Label: maintain vineyard machinery, Job Count: 1, Job IDs: [72877]
Skill ID: http://data.europa.eu/esco/skill/e7c47c8c-7110-4c56-bca1-f56a2c3ed11b, Label: phytosanitary measures, Job Count: 1, Job IDs: [72877]
Skill ID: http://data.europa.eu/esco/skill/cacb30e8-eb78-40bf-b664-b7a4c8a018a3, Label: milk animals, Job Count: 1, Job IDs: [1702319]
Skill ID: http://data.europa.eu/esco/skill/0e9fbf47-0cec-4d82-97f9-12a3334819fe, Label: control animal movement, Job Count: 1, Job IDs: [1870403]
Skill ID: http://data.europa.eu/esco/skill/dc3421a2-e1e6-4535-a645-a0440acca9e8, Label: work independently in agriculture, Job Count: 1, Job IDs: [1887173]
Skill ID: http://data.europa.eu/esco/skill/9ba33cce-53f4-4cde-b473-f9707569fcea, Label: perform farm equipment hygiene, Job Count: 1, Job IDs: [1889800]
Skill ID: http://data.europa.eu/esco/skill/9c2f2331-960f-41ee-a2c9-d26e258a156e, Label: spray pesticides, Job Count: 1, Job IDs: [1923458]
Skill ID: http://data.europa.eu/esco/skill/e85cff6b-ee0e-4106-98f0-b57b39a2ea3f, Label: execute disease and pest control activities, Job Count: 1, Job IDs: [1751210]
Skill ID: http://data.europa.eu/esco/skill/7503647a-72f8-40fc-a88a-1e884429f85f, Label: care for the flock, Job Count: 1, Job IDs: [1807209]
Skill ID: http://data.europa.eu/esco/skill/77390acd-7cf6-4cb2-895a-16bc6b6d2058, Label: wildlife, Job Count: 1, Job IDs: [1880872]
Skill ID: http://data.europa.eu/esco/skill/5125b132-d1a9-41a4-95c3-91b0984e86b5, Label: maintain ground, Job Count: 1, Job IDs: [1958636]
Skill ID: http://data.europa.eu/esco/skill/6d53015b-6867-408f-8f3a-4eb9d5dae101, Label: maintain plant soil nutrition, Job Count: 1, Job IDs: [1958636]

# Converting and saving relevant skills as csv file

In [ ]:
def save_skills_to_csv(sorted_skills):
    skill_data = []
    for skill_id, skill_info in sorted_skills:
        skill_data.append({
            'skill_label': skill_info['label'], 'skill_id': skill_id, 'job_count': skill_info['job_count'], 'job_ids': skill_info['job_ids']
        })

    df_relevant_skills = pd.DataFrame(skill_data)

    try:
      df_relevant_skills.to_csv('relevant_skills.csv', index=False)
      print("DataFrame 'df_relevant_skills' successfully saved to 'relevant_skills.csv'")

    except Exception as e:
      print(f"Error saving DataFrame to CSV: {e}")

save_skills_to_csv(sorted_skills)

DataFrame 'df_relevant_skills' successfully saved to 'relevant_skills.csv'

In [ ]:
import pandas as pd


df = pd.read_csv("/content/relevant_skills.csv")


df.head()

,skill_label,skill_id,job_count,job_ids
0,harvest crop,http://data.europa.eu/esco/skill/2e4e8114-e579...,35,"[32661, 52208, 63540, 80351, 91684, 109562, 11..."
1,crop production principles,http://data.europa.eu/esco/skill/4ca83b9d-afa0...,35,"[141059, 151290, 156338, 156744, 184552, 16474..."
2,agroecology,http://data.europa.eu/esco/skill/c4b03a17-a93e...,29,"[32661, 45646, 45647, 45653, 52208, 61744, 635..."
3,manage crop production,http://data.europa.eu/esco/skill/754de174-292f...,25,"[82355, 92925, 123970, 145804, 156728, 156744,..."
4,research improvement of crop yields,http://data.europa.eu/esco/skill/b47da85a-bfde...,25,"[156728, 156744, 184552, 1663135, 1663151, 168..."

In [ ]:
import pandas as pd

def save_jobs_to_csv(sorted_skills):
    if jobs_data.get('items'):
        df_jobs_data = pd.DataFrame(jobs_data['items'])
        try:
            df_jobs_data.to_csv('all_jobs_data.csv', index=False)
            print("DataFrame 'df_jobs_data' successfully saved to 'all_jobs_data.csv'")
        except Exception as e:
            print(f"Error saving DataFrame 'df_jobs_data' to CSV: {e}")
    else:
        print("jobs_data not found or is empty.")

def save_accepted_jobs_to_csv(accepted):
    if accepted:
        df_accepted_jobs = pd.DataFrame(list(accepted.values()))
        try:
            df_accepted_jobs.to_csv('accepted_jobs.csv', index=False)
            print("DataFrame 'df_accepted_jobs' successfully saved to 'accepted_jobs.csv'")
        except Exception as e:
            print(f"Error saving DataFrame 'df_accepted_jobs' to CSV: {e}")
    else:
        print("accepted not found or is empty.")

save_jobs_to_csv(sorted_skills)
save_accepted_jobs_to_csv(accepted)

DataFrame 'df_jobs_data' successfully saved to 'all_jobs_data.csv'
DataFrame 'df_accepted_jobs' successfully saved to 'accepted_jobs.csv'

In [ ]:
import pandas as pd

df = pd.read_csv("/content/all_jobs_data.csv")
print("--- all jobs ---")
display(df.head())

df1 = pd.read_csv("/content/accepted_jobs.csv")
print("\n--- accepted jobs ---")
display(df1.head())

--- all jobs ---

,skills,occupations,id,organization,title,description,experience_level,type,location,location_code,nuts1,nuts2,nuts3,upload_date,source,source_id
0,['http://data.europa.eu/esco/skill/435d1751-86...,['http://data.europa.eu/esco/occupation/1b5ccf...,1659,NaN,MANAGER OF PRODUCTION,"MILIORA FARM SA, which operates a modern sheep...",Entry / Junior,Full-time,"Larissos, Greece",EL,NaN,NaN,NaN,2024-09-03,kariera.gr,166734
1,['http://data.europa.eu/esco/skill/63f224ea-d8...,['http://data.europa.eu/esco/occupation/1b5ccf...,2638,NaN,Agricultural Sales - Export Managers,The Fertilizer Industry\nD. GAVRIEL & CO LTD\n...,Mid-level,Full-time,"Athens, Greece",EL,NaN,NaN,NaN,2024-08-29,kariera.gr,165914
2,['http://data.europa.eu/esco/skill/568e4759-c6...,['http://data.europa.eu/esco/occupation/08984b...,2893,NaN,Farm Veterinarian,"EPIROS SA, with a strong presence in the chees...",Senior,Full-time,"Larisa, Greece",EL,NaN,NaN,NaN,2024-08-28,kariera.gr,165616
3,['http://data.europa.eu/esco/skill/568e4759-c6...,['http://data.europa.eu/esco/occupation/08984b...,3237,NaN,Veterinary,"EPIROS SA, with a strong presence in the chees...",Senior,Full-time,"Ioannina, Greece",EL,NaN,NaN,NaN,2024-08-27,kariera.gr,165198
4,['http://data.europa.eu/esco/skill/0da516ee-e7...,['http://data.europa.eu/esco/occupation/11e6d3...,6744,NaN,Senior Consultant Agriculture and Food Sector F/M,"Position Description: You will join CGI, the w...",NaN,Full-time,"Rennes, France",FR,NaN,NaN,NaN,2024-09-05,lesjeudis,120054

--- accepted jobs ---

,skills,occupations,id,organization,title,description,experience_level,type,location,location_code,nuts1,nuts2,nuts3,upload_date,source,source_id
0,['http://data.europa.eu/esco/skill/435d1751-86...,['http://data.europa.eu/esco/occupation/1b5ccf...,1659,NaN,MANAGER OF PRODUCTION,"MILIORA FARM SA, which operates a modern sheep...",Entry / Junior,Full-time,"Larissos, Greece",EL,NaN,NaN,NaN,2024-09-03,kariera.gr,166734
1,['http://data.europa.eu/esco/skill/568e4759-c6...,['http://data.europa.eu/esco/occupation/08984b...,2893,NaN,Farm Veterinarian,"EPIROS SA, with a strong presence in the chees...",Senior,Full-time,"Larisa, Greece",EL,NaN,NaN,NaN,2024-08-28,kariera.gr,165616
2,['http://data.europa.eu/esco/skill/568e4759-c6...,['http://data.europa.eu/esco/occupation/08984b...,3237,NaN,Veterinary,"EPIROS SA, with a strong presence in the chees...",Senior,Full-time,"Ioannina, Greece",EL,NaN,NaN,NaN,2024-08-27,kariera.gr,165198
3,['http://data.europa.eu/esco/skill/0da516ee-e7...,['http://data.europa.eu/esco/occupation/11e6d3...,6744,NaN,Senior Consultant Agriculture and Food Sector F/M,"Position Description: You will join CGI, the w...",NaN,Full-time,"Rennes, France",FR,NaN,NaN,NaN,2024-09-05,lesjeudis,120054
4,['http://data.europa.eu/esco/skill/2e77d381-df...,['http://data.europa.eu/esco/occupation/1765f9...,28966,NaN,Versatile agricultural worker M/F,Agricultural Worker on permanent contract - Ag...,NaN,Full-time,"Castelnau-Magnoac, France",FR,NaN,NaN,NaN,2024-09-05,kariera.fr,1527768